package replicatedstate

import (
	"bytes"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sync"

	"github.com/thesyncim/vibedb/internal/storeio"
)

// SnapshotCursorStore owns one crash-durable, atomically replaced resume
// cursor and an advisory single-writer lease in a pinned directory namespace.
// It stores no artifact rows; those live only in the non-serving collections.
type SnapshotCursorStore struct {
	mu sync.Mutex

	root     *os.Root
	base     string
	lockFile *os.File
	raw      []byte
	closed   bool
}

// OpenSnapshotCursorStore opens or creates the writer lease for path and
// strictly recovers its current cursor when present. Symlinks, non-regular
// entries, oversized files, and conflicting writers fail closed.
func OpenSnapshotCursorStore(path string) (*SnapshotCursorStore, error) {
	if path == "" {
		return nil, fmt.Errorf("%w: empty cursor path", ErrSnapshotStage)
	}
	parent, base := filepath.Dir(path), filepath.Base(path)
	if base == "" || base == "." || base == ".." || filepath.Join(parent, base) != filepath.Clean(path) {
		return nil, fmt.Errorf("%w: cursor path", ErrSnapshotStage)
	}
	root, err := os.OpenRoot(parent)
	if err != nil {
		return nil, err
	}
	lockFile, err := openSnapshotCursorEntry(root, base+".lock", os.O_RDWR|os.O_CREATE, 0o600)
	if err != nil {
		_ = root.Close()
		return nil, err
	}
	if err := storeio.LockWriter(lockFile); err != nil {
		_ = lockFile.Close()
		_ = root.Close()
		return nil, fmt.Errorf("%w: cursor writer: %v", ErrSnapshotStage, err)
	}
	store := &SnapshotCursorStore{root: root, base: base, lockFile: lockFile}
	raw, err := store.readCurrent()
	if err != nil {
		_ = store.Close()
		return nil, err
	}
	store.raw = raw
	return store, nil
}

// Load returns a detached copy of the current cursor. Nil means no chunk has
// been durably checkpointed.
func (s *SnapshotCursorStore) Load() ([]byte, error) {
	if s == nil {
		return nil, fmt.Errorf("%w: nil cursor store", ErrSnapshotStage)
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return nil, fmt.Errorf("%w: cursor store closed", ErrSnapshotStage)
	}
	return bytes.Clone(s.raw), nil
}

// Persist atomically advances the cursor. Exact retries are idempotent;
// regressions and a cursor from another artifact are refused. raw is borrowed
// only for the call.
func (s *SnapshotCursorStore) Persist(raw []byte) error {
	if s == nil {
		return fmt.Errorf("%w: nil cursor store", ErrSnapshotStage)
	}
	next, err := OpenSnapshotArtifactCursor(raw)
	if err != nil {
		return err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return fmt.Errorf("%w: cursor store closed", ErrSnapshotStage)
	}
	if bytes.Equal(raw, s.raw) {
		return nil
	}
	if len(s.raw) != 0 {
		current, err := OpenSnapshotArtifactCursor(s.raw)
		if err != nil {
			return err
		}
		currentPrefix, nextPrefix := current.PrefixManifest(), next.PrefixManifest()
		if next.Offset() <= current.Offset() ||
			next.NextSequence() <= current.NextSequence() ||
			!equalState(currentPrefix.State, nextPrefix.State) ||
			!bytes.Equal(currentPrefix.UserCollection, nextPrefix.UserCollection) ||
			currentPrefix.TargetChunkBytes != nextPrefix.TargetChunkBytes ||
			currentPrefix.HeaderDigest != nextPrefix.HeaderDigest {
			return fmt.Errorf("%w: cursor does not monotonically advance", ErrSnapshotStage)
		}
	}
	temporary, err := s.createTemporary()
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	// os.Root file names are not required to preserve the caller-visible full
	// path, so retain the exact basename generated by createTemporary.
	temporaryBase := filepath.Base(temporaryName)
	renamed := false
	defer func() {
		if !renamed {
			_ = s.root.Remove(temporaryBase)
		}
	}()
	if err := writeSnapshotArtifactBytes(temporary, raw); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Sync(); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := replaceSnapshotCursorEntry(s.root, temporaryBase, s.base); err != nil {
		return err
	}
	renamed = true
	if err := syncSnapshotCursorRoot(s.root); err != nil {
		return errors.Join(ErrSnapshotStageOutcomeUnknown, err)
	}
	s.raw = bytes.Clone(raw)
	return nil
}

func (s *SnapshotCursorStore) createTemporary() (*os.File, error) {
	var nonce [16]byte
	for attempts := 0; attempts < 100; attempts++ {
		if _, err := cryptorand.Read(nonce[:]); err != nil {
			return nil, err
		}
		name := "." + s.base + ".tmp-" + hex.EncodeToString(nonce[:])
		file, err := s.root.OpenFile(name, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0o600)
		if err == nil {
			return file, nil
		}
		if !errors.Is(err, os.ErrExist) {
			return nil, err
		}
	}
	return nil, fmt.Errorf("%w: cannot allocate cursor temporary", ErrSnapshotStage)
}

func (s *SnapshotCursorStore) readCurrent() ([]byte, error) {
	file, err := openSnapshotCursorEntry(s.root, s.base, os.O_RDONLY, 0)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return nil, err
	}
	if info.Size() < snapshotArtifactCursorFixedBytes+sha256.Size ||
		info.Size() > maxSnapshotArtifactCursorBytes {
		return nil, fmt.Errorf("%w: cursor file size", ErrSnapshotArtifact)
	}
	raw := make([]byte, int(info.Size()))
	if _, err := io.ReadFull(file, raw); err != nil {
		return nil, err
	}
	if _, err := OpenSnapshotArtifactCursor(raw); err != nil {
		return nil, err
	}
	return raw, nil
}

// Close releases the writer lease and pinned namespace. It is idempotent.
func (s *SnapshotCursorStore) Close() error {
	if s == nil {
		return nil
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return nil
	}
	s.closed = true
	err := errors.Join(storeio.UnlockWriter(s.lockFile), s.lockFile.Close(), s.root.Close())
	s.lockFile = nil
	s.root = nil
	return err
}

func openSnapshotCursorEntry(
	root *os.Root,
	name string,
	flags int,
	mode os.FileMode,
) (*os.File, error) {
	var before os.FileInfo
	var err error
	if flags&os.O_CREATE == 0 {
		before, err = root.Lstat(name)
		if err != nil {
			return nil, err
		}
		if !before.Mode().IsRegular() {
			return nil, fmt.Errorf("%w: cursor entry is not regular", ErrSnapshotStage)
		}
	}
	file, err := root.OpenFile(name, flags, mode)
	if err != nil {
		return nil, err
	}
	opened, openErr := file.Stat()
	entry, entryErr := root.Lstat(name)
	stable := openErr == nil && entryErr == nil && opened.Mode().IsRegular() &&
		entry.Mode().IsRegular() && os.SameFile(opened, entry)
	if before != nil {
		stable = stable && os.SameFile(before, entry)
	}
	if !stable {
		_ = file.Close()
		if openErr != nil {
			return nil, openErr
		}
		if entryErr != nil {
			return nil, entryErr
		}
		return nil, fmt.Errorf("%w: unstable cursor entry", ErrSnapshotStage)
	}
	return file, nil
}
