package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"

	"github.com/thesyncim/vibedb/internal/buildgate/manifestgen"
	"github.com/thesyncim/vibedb/internal/requestledger"
)

func main() {
	manifestPath := flag.String("manifest", "", "canonical build manifest")
	outputPath := flag.String("output", "", "generated Go output")
	flag.Parse()
	if *manifestPath == "" || *outputPath == "" || flag.NArg() != 0 {
		fatalf("manifest and output are required")
	}
	raw, err := os.ReadFile(*manifestPath)
	if err != nil {
		fatalf("read manifest: %v", err)
	}
	semantics := requestledger.SemanticsDigest()
	wire, disk, err := manifestgen.Derive(raw, [32]byte(semantics))
	if err != nil {
		fatalf("derive identities: %v", err)
	}
	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by buildgategen; DO NOT EDIT.")
	fmt.Fprintln(&source, "package buildgate")
	fmt.Fprintf(&source, "\nvar generatedWireGrammar = GrammarID{%s}\n", byteList(wire[:]))
	fmt.Fprintf(&source, "var generatedDiskGrammar = GrammarID{%s}\n", byteList(disk[:]))
	fmt.Fprintf(&source, "var generatedRequestLedgerSemantics = [32]byte{%s}\n", byteList(semantics[:]))
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fatalf("format output: %v", err)
	}
	if err := os.WriteFile(*outputPath, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
}

func byteList(raw []byte) string {
	var out bytes.Buffer
	for index, value := range raw {
		if index != 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(&out, "0x%02x", value)
	}
	return out.String()
}

func fatalf(pattern string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "buildgategen: "+pattern+"\n", arguments...)
	os.Exit(1)
}
