// Package featurestate owns the evidence-backed distributed feature ledger.
//
// The manifest is the source of truth for docs/distributed-feature-state.md.
// It distinguishes code that exists from code that is integrated, exposed by
// the repository's commands, and qualified under a fault or benchmark gate.
package featurestate

//go:generate go run ./cmd/featurestategen -out ../../docs/distributed-feature-state.md

type Status uint8

const (
	StatusNo Status = iota
	StatusPartial
	StatusYes
)

func (s Status) label() string {
	switch s {
	case StatusYes:
		return "Yes"
	case StatusPartial:
		return "Partial"
	default:
		return "No"
	}
}

type Reference struct {
	Path   string
	Symbol string
}

type Stage struct {
	Status   Status
	Contract string
	Evidence []Reference
}

type Feature struct {
	Name          string
	Primitive     Stage
	Integrated    Stage
	Shipped       Stage
	Qualification Stage
}

func ref(path, symbol string) Reference {
	return Reference{Path: path, Symbol: symbol}
}

// Distributed is deliberately conservative. A correctness test is not a
// fault or benchmark gate. A package used only by another internal package is
// not a checked-in development command. No row predicts work from an open branch.
var Distributed = []Feature{
	{
		Name: "Static shard routing and scatter reads",
		Primitive: Stage{StatusYes, "The catalog, planner, router, merge path, and bounded fanout exist.", []Reference{
			ref("gateway/catalog.go", "Snapshot"), ref("gateway/executor.go", "Executor"),
		}},
		Integrated: Stage{StatusYes, "The gateway executor sends SQL to leader-only shard services and merges complete results.", []Reference{
			ref("gateway/e2e_test.go", "TestE2EFanoutShapes"), ref("shardservice/server.go", "Server"),
		}},
		Shipped: Stage{StatusYes, "vibedb-gateway serve and vibedb-shard serve expose this static-ownership path.", []Reference{
			ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("cmd/vibedb-shard/main.go", "runServe"),
		}},
		Qualification: Stage{StatusPartial, "Correctness, stale-catalog, admission, and merge tests exist. There is no external kill or scaling benchmark gate for this command path.", []Reference{
			ref("gateway/e2e_test.go", "TestE2EFanoutShapes"), ref("gateway/executor_test.go", "TestExecutorFailClosedOnShardError"),
		}},
	},
	{
		Name: "Authenticated and authorized service transport",
		Primitive: Stage{StatusYes, "TLS 1.3 profiles bind node identity, traffic class, trust roots, and limits. Canonical vibejson policies bind exact principals and generations to fixed capabilities.", []Reference{
			ref("internal/servicetls/server.go", "Server"), ref("internal/serviceauthz/policy.go", "Policy"),
		}},
		Integrated: Stage{StatusYes, "The gateway authorizes complete request semantics and forwards the exact client authority. Shards independently check it while requiring a delegate-capable gateway.", []Reference{
			ref("gateway/client_tls.go", "ServeAuthorizedClients"), ref("shardservice/server.go", "ServeAuthorizedConn"),
		}},
		Shipped: Stage{StatusYes, "The gateway and static shard commands require TLS plus an authorization policy unless the operator selects explicit loopback development plaintext. The RF3 shard command is always authenticated.", []Reference{
			ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("cmd/vibedb-shard/main.go", "runServe"), ref("cmd/vibedb-shard/serve_rf3.go", "runServeRF3"),
		}},
		Qualification: Stage{StatusPartial, "Tests cover complete parsed SQL semantics, identity, generation rotation, confused-deputy refusal, connection bounds, and allocation contracts. Real TCP TLS gates cover client-to-gateway handshake churn and gateway-to-shard independent delegate and forwarded-principal checks. An external shard process gate sustains requests across a directional partition and healing, rotates its certificate generation while revoking the old stream, and rejects both a rogue gateway certificate and a confused-deputy request. TestGatewayDurableRF3ExternalProcessRecovery adds the checked-in development gateway command with distinct gateway principals and native mutual TLS across client, gateway, catalog, request-ledger, and two data RF3 groups. Hot authorization is allocation-free; the steady-stream benchmark keeps the standard crypto/tls per-record read allocation floor separate and visible. This remains Partial because the complete process gate does not combine certificate-rotation and confused-deputy faults across the whole gateway command path.", []Reference{
			ref("internal/serviceauthz/sql_test.go", "TestSQLCapabilityRequiresCompleteParsedSemantics"), ref("gateway/client_tls_test.go", "TestClientTLSAuthenticatesAuthorizesRotatesAndSeparatesALPN"), ref("gateway/client_tls_qualification_test.go", "TestAuthorizedClientTLSNetworkChaosAndThroughputGate"), ref("gateway/client_tls_qualification_test.go", "BenchmarkAuthorizedClientTLSRequest"), ref("gateway/shard_tls_qualification_test.go", "TestAuthenticatedShardBoundaryRotationAndConfusedDeputyFault"), ref("gateway/shard_tls_qualification_test.go", "TestAuthenticatedGatewayShardHotAuthorizationAllocationFree"), ref("gateway/shard_tls_qualification_test.go", "BenchmarkAuthenticatedGatewayShardStream"), ref("gateway/shard_tls_process_qualification_test.go", "TestAuthenticatedGatewayShardProcessPartitionRotationAndDeputyFaults"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"), ref("shardservice/authorization_test.go", "TestShardAuthorizationRejectsConfusedDeputyAndSeparatesRoles"),
		}},
	},
	{
		Name: "Coherent multi-shard reads",
		Primitive: Stage{StatusYes, "Bounded static read fences establish one scoped vector cut. RF3 exact-key batch reads return an explicit sorted observation vector. General SQL SELECT plans use independent leader ReadIndex cuts but expose no public observation vector; none of these contracts claims one global MVCC timestamp.", []Reference{
			ref("gateway/read_snapshot.go", "snapshotFanout"), ref("gateway/replicated_sql_read.go", "ReadSQLBatch"), ref("gateway/replicated_query.go", "ReplicatedSQLTransport"),
		}},
		Integrated: Stage{StatusYes, "The static gateway acquires all fences before fanout. In replicated-catalog mode the ordinary SQL planner resolves each pinned physical target through ReplicatedSQLTransport, follows its RF3 leader, executes after ReadIndex, and reuses bounded target/scatter merge. The narrower RF3 reader folds exact-key statements by group, bounds parallel reads and response bytes, and refuses every partial result.", []Reference{
			ref("gateway/read_snapshot.go", "snapshotFanout"), ref("gateway/replicated_query.go", "ReplicatedSQLTransport"), ref("gateway/replicated_sql_read.go", "ReadSQLBatch"),
		}},
		Shipped: Stage{StatusYes, "The query operation is mode-dependent: explicit development/static catalog mode uses the static shard transport, while replicated-catalog mode sends supported general SELECT plans through RF3. RF3 supports bounded targeted/scatter reads, projection, global order/limit, and mergeable aggregates; global-index read and repartition-exchange plans are refused, and the public query response exposes no observation vector. read_batch separately serves ordered multi-table and multi-group exact-primary-key reads with an explicit vector.", []Reference{
			ref("internal/gatewayruntime/serve.go", "newReplicatedCatalogGateway"), ref("gateway/replicated_query.go", "QuerySQL"), ref("internal/gatewayruntime/data_sql_batch.go", "buildNativeSQLBatchReadRequest"),
		}},
		Qualification: Stage{StatusPartial, "Static lease, cleanup, stale-refusal, and pinned-snapshot tests exist. RF3 general-SQL tests exercise targeted/scatter SELECTs, global order, aggregate merge, leader routing, internal cut accounting, and all-or-nothing failure. RF3 read_batch tests prove same-group multi-relation cuts, cross-group vectors, all-or-nothing byte admission, and bounded execution across 65 groups. Mandatory external process gates cover the exact-key lane across a bidirectional Raft peer-network partition with the isolated process live, a killed leader, delayed response, gateway replacement, and rolling recovery while bounding failover, p99, RSS, storage, WAL, and exact public wire bytes; they do not qualify general RF3 SQL, so the row remains Partial.", []Reference{
			ref("shardservice/read_fence_test.go", "TestReadFenceLeaseExpiresAndWakesWriter"), ref("gateway/replicated_query_test.go", "TestRF3SQLReusesTargetingScatterGlobalOrderAndAggregate"), ref("internal/gatewayruntime/data_sql_batch_test.go", "TestReadBatchWireSixtyFiveGroupsIsBoundedAndUncapped"), ref("internal/gatewayruntime/data_sql_batch_test.go", "TestReadBatchWireExactByteBoundAndIntentNeverReturnPartialValues"), ref("internal/gatewayruntime/read_batch_rf3_external_process_test.go", "TestGatewayReadBatchRF3ExternalProcessChaos"),
		}},
	},
	{
		Name: "Bounded distributed metrics",
		Primitive: Stage{StatusYes, "Fixed-width counters and gauges observe proposal commands and bytes, authoritative commit-index advancements and committed entries, applied entries, persisted Ready steps, snapshot apply, ReadIndex completion, Raft faults, checkpoints, WAL, backup, snapshot transfer, replica actions, split control, and target bootstrap. Group and node cuts use no unbounded labels.", []Reference{
			ref("internal/raftservice/progress_metrics.go", "ProgressMetrics"), ref("internal/servicemetrics/service.go", "StageMetricsSnapshot"),
		}},
		Integrated: Stage{StatusYes, "The authenticated shard-control service returns one exact group/member cut or one node-stage aggregate. The gateway fixes the complete catalog directory, refreshes it with bounded workers and deadlines, publishes through seqlocks, and computes saturating lock-free aggregates without request-path sample storage. Split and move controller loops update fixed atomics from their actual pass results.", []Reference{
			ref("internal/servicemetrics/service.go", "Service"), ref("gateway/distributed_metrics.go", "DistributedMetrics"), ref("gateway/distributed_metrics.go", "DistributedMetricsAggregate"), ref("internal/gatewayruntime/controller_metrics.go", "gatewayControllerMetrics"),
		}},
		Shipped: Stage{StatusYes, "serve-rf3 and the cold target bootstrap mux install the fixed 80-byte request and 408-byte topology-authorized response. A replicated vibedb-gateway metrics response directly encodes process routing counters, cluster aggregate, overflow, bounded member and node cuts, and configured split/move controller progress with vibejson. Telemetry never authorizes routing, membership, split, move, cleanup, or acknowledgement.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("cmd/vibedb-shard/rf3_metrics.go", "rf3MetricsProvider"), ref("internal/gatewayruntime/serve_metrics.go", "writeGatewayDistributedMetrics"), ref("internal/gatewayruntime/serve_metrics.go", "writeGatewayControllerMetrics"),
		}},
		Qualification: Stage{StatusPartial, "Known defect: a nonzero-group request can panic when Service was constructed with a Provider that does not also implement GroupProvider. Group-serving configurations must supply GroupProvider. Tests otherwise cover exact group identity, node-stage framing, authentication before read, corruption, duplicate and wrong-member refusal, saturating aggregation, actual controller-pass observation, and canonical direct encoding. Benchmarks check the counter hot path, codec, cached snapshot, controller snapshot, and gateway encoding allocation contracts at zero allocations. There is no mandatory external slow-scrape, member-churn, very-wide-directory, or long-running telemetry-overhead gate. ready_persisted is not a quorum counter. The authoritative commit counters do not measure quorum latency or bytes. Leadership, exact split and move phase, latency histograms, total network, and physical device writes are not exported.", []Reference{
			ref("internal/servicemetrics/service.go", "Serve"), ref("internal/raftservice/progress_metrics_test.go", "TestProgressMetricsCountsExistingOwnerSeamsExactly"), ref("internal/servicemetrics/service_test.go", "TestMetricsNodeStageSnapshotIsAuthenticatedAndCanonical"), ref("gateway/distributed_metrics_test.go", "TestDistributedMetricsAuthenticatedExactGroupRefresh"), ref("gateway/distributed_metrics_test.go", "BenchmarkDistributedMetricsSnapshotInto"), ref("internal/gatewayruntime/controller_metrics_test.go", "TestGatewayControllerMetricsObserveActualPasses"), ref("internal/gatewayruntime/serve_metrics_test.go", "BenchmarkWriteGatewayDistributedMetrics"),
		}},
	},
	{
		Name: "Distributed clock model and skew resilience",
		Primitive: Stage{StatusYes, "RF3 order and reads use Raft term, index, applied index, and ReadOnlySafe. Transaction recovery advances bounded replicated pulses. Execution-pin leases and hot-shard cooldown use replicated progress fences instead of elapsed time.", []Reference{
			ref("internal/raftmodel/config.go", "NewConfig"), ref("internal/executionpin/command.go", "Command"), ref("internal/distributedtxn/journal.go", "Journal"),
		}},
		Integrated: Stage{StatusYes, "Static and RF3 transaction recovery require an ordered pulse sequence before abort. The durable request lifecycle binds one clockless controller epoch and applied-index lease to the complete program. Pressure evidence uses catalog generations and authority revisions.", []Reference{
			ref("gateway/recovery.go", "recoverCoordinator"), ref("gateway/replicated_request_execution_context.go", "BuildDurableRequestExecutionPinBinding"), ref("internal/hotshard/controller.go", "Controller"),
		}},
		Shipped: Stage{StatusYes, "The RF3 command path uses quorum order, applied-index reads, vector cuts, logical recovery pulses, and the checked-in durable request service's applied-index execution pins. Local time controls only TLS validity, network/context deadlines, retry scheduling, catalog-session deadline construction, and the separate static read-fence lane.", []Reference{
			ref("internal/gatewayruntime/serve.go", "execRequest"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/rafttransport/identity.go", "PeerTLS"),
		}},
		Qualification: Stage{StatusPartial, "A bounded Linux command matrix composes independently injected peer UTC steps and TLS validity, logical-pulse restart recovery, two-group leader isolation and exact transaction retry, real process suspend/resume, former-leader refusal, foreground failover latency, and the checked-in serve-rf3 kill/partition pressure gate. Skips fail the matrix and evidence bytes are bounded. Live database-process UTC is not changed, and arbitrary static read-fence suspension/overrun remains unqualified, so this is not a global timestamp or unrestricted clock-fault claim.", []Reference{
			ref("internal/rafttransport/clock_fault_matrix_test.go", "TestPeerTLSIndependentUTCStepMatrix"), ref("gateway/recovery_test.go", "TestRecoveryManifestMissingPageRequiresLogicalPulsesAcrossRestart"), ref("internal/raftservice/owner_rf3_multigroup_transaction_test.go", "TestTwoRealRF3GroupsExecuteFusedTwoTargetTransactionAcrossLeaderIsolation"), ref("internal/raftservice/process_rf3_test.go", "TestRF3NativeServingThreeProcessRecoveryEvidence"), ref("cmd/vibedb-shard/serve_rf3_fault_process_test.go", "TestServeRF3ShippedFaultHarness"),
		}},
	},
	{
		Name: "Byte-bounded distributed transactions",
		Primitive: Stage{StatusYes, "Compact inline and root-bound paged coordinator manifests implement prepare, decision, apply, release, retry, and bounded recovery without a participant-count contract.", []Reference{
			ref("internal/distributedtxn/manifest.go", "ManifestBuilder"), ref("gateway/transaction.go", "executeTransaction"),
		}},
		Integrated: Stage{StatusYes, "ExecBatch and global-index writes select the inline fast path or stream segmented manifests through the authenticated shard protocol and paged recovery.", []Reference{
			ref("gateway/transaction_manifest.go", "stageTransactionCoordinator"), ref("gateway/recovery.go", "recoverManifestCoordinator"),
		}},
		Shipped: Stage{StatusPartial, "Static vibedb-gateway serve can invoke the transaction engine behind one single-base-owner exec when independently placed index maintenance adds participants. It does not expose general multi-statement or cross-base-shard static exec_batch; public exec_batch is reserved for authenticated durable RF3 and refuses every unsequenced fallback.", []Reference{
			ref("internal/gatewayruntime/serve.go", "execRequest"), ref("gateway/executor.go", "Exec"), ref("internal/gatewayruntime/serve_test.go", "TestServeGatewayStaticWriteSurface"),
		}},
		Qualification: Stage{StatusPartial, "Known defect: journal compaction omits coordinator recovery-pulse records, so reopen after compaction can reset pulse state. Do not rely on that path for recovery authority. Library-level tests prove a real 65-shard segmented transaction, readback, outcome-unknown handling, multi-page restart, malformed-page refusal, idempotency, recovery, and failure atomicity. A public static-listener test proves exec_batch cannot reach that engine through an unsequenced fallback. No checked-in static command path exists to qualify under external kill, partition, or scaling gates.", []Reference{
			ref("internal/distributedtxn/journal.go", "PulseCoordinator"), ref("internal/distributedtxn/journal_compact.go", "compactedBytesLocked"), ref("gateway/segmented_e2e_test.go", "TestSegmentedExecBatchAcross65RealShardServers"), ref("gateway/segmented_e2e_test.go", "TestSegmentedCoordinatorResponseLossAndRestartBoundaries"), ref("internal/gatewayruntime/serve_test.go", "TestServeGatewayStaticWriteSurface"),
		}},
	},
	{
		Name: "Fused multi-shard RF3 transaction orchestration",
		Primitive: Stage{StatusYes, "Fresh replicated operations atomically combine coordinator begin with its local prepare, remote stage with prepare, and participant apply or abort with release. Inline and greedily packed manifests remain byte-bounded without a participant-count contract.", []Reference{
			ref("internal/distributedtxn/replicated_codec.go", "ReplicatedOperation"), ref("internal/replicatedstate/transaction_apply.go", "planCoordinatorBeginPrepare"),
		}},
		Integrated: Stage{StatusYes, "The SQL lowerer can read one exact-key old row, evaluate supported computed UPDATE assignments once, and seal the canonical postimage plus exact old-value CAS into the participant program. The durable request runner streams that owned program, builds exact fused commands, stages their bytes before proposal, and recovers from replicated ReadIndex witnesses without re-evaluating SQL. Aggregate execution-pin epochs fence takeover locally at every participant while one home-group proof admits each persisted wave.", []Reference{
			ref("gateway/replicated_sql_transaction.go", "planReplicatedSQLTransaction"), ref("gateway/replicated_request_transaction_runner.go", "DurableRequestDistributedRunner"), ref("gateway/replicated_request_lifecycle_runner.go", "RunWave"), ref("gateway/replicated_transaction_protocol.go", "replicatedTransactionCommandEncoder"),
		}},
		Shipped: Stage{StatusYes, "vibedb-gateway accepts only authenticated structured issuer identities for RF3 exec_batch, lowers complete-document or canonical column-list INSERT rows plus supported exact-key UPDATE/DELETE across one or more tables and global-index relations, including computed top-level declared-column UPDATE assignments, performs fused durable admission, and returns the terminal result with an authenticated ACK capability. One multi-row INSERT may span RF3 groups. There is no process-local request registry or legacy RF3 fallback.", []Reference{
			ref("gateway/durable_sql_request_executor.go", "Execute"), ref("internal/gatewayruntime/durable_request_adapter.go", "ExecBatch"), ref("internal/gatewayruntime/serve.go", "newReplicatedCatalogGateway"),
		}},
		Qualification: Stage{StatusPartial, "State-machine, SQL lowering, schedule, durable lifecycle, and exact-retry gates cover canonical flat INSERT encoding, cross-shard multi-row INSERT, retained computed-update postimages and old-value CAS, planner-error replay of an authenticated retained program, atomic transitions, bounded reclamation, concurrent gateways, and the fused 2P+1 decision/apply schedule without a participant-count contract. Real in-process RF3 gates prove two independently led data groups, a dedicated request-ledger group, isolation, exact hidden-command retry, replacement-gateway terminal replay, ACK recovery, replica convergence, and former-leader refusal. TestGatewayDurableRF3ExternalProcessRecovery adds three shard processes that each host catalog, request-ledger, and two data RF3 groups, native mutual TLS, distinct replacement-gateway principals and route seeds, a stopped voter, killed leaders, lost terminal and ACK responses, exact replay, and rolling voter restarts. Its workload does not exercise computed UPDATE expressions and its byte bounds omit total Raft and network traffic, so the row remains Partial.", []Reference{
			ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLFlatInsertUsesCanonicalRuntimeDocuments"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLFlatInsertRoutesAcrossDataShards"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLComputedUpdateRetainsCanonicalExactCAS"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLComputedPostimageIsOwnedByDurableLogicalProgram"), ref("gateway/durable_sql_request_executor_test.go", "TestDurableSQLComputedUpdateRetryRecoversRetainedProgramAfterReevaluationError"), ref("internal/replication/transaction_perf_contract_test.go", "TestReplicatedTransactionEncodedSchedulePerformanceTargets"), ref("internal/raftservice/owner_rf3_multigroup_transaction_test.go", "TestTwoRealRF3GroupsExecuteFusedTwoTargetTransactionAcrossLeaderIsolation"), ref("internal/raftservice/owner_rf3_request_ledger_test.go", "TestTwoGatewayDurableSQLRF3RecoversTerminalAndAckAcrossLeaderPartitions"), ref("gateway/replicated_request_ledger_fault_test.go", "TestDurableRequestReplacementRecoversEveryReplicatedBoundary"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"),
		}},
	},
	{
		Name: "RF3 transaction recovery reads",
		Primitive: Stage{StatusYes, "A closed hidden-state reader provides exact coordinator and participant lookup, paged manifest access, and bounded resumable active-coordinator scans without a participant-count contract.", []Reference{
			ref("internal/replicatedstate/transaction_recovery_read.go", "TransactionRecoveryReadInto"), ref("internal/replicatedstate/transaction_recovery_read.go", "TransactionRecoveryReadRequest"),
		}},
		Integrated: Stage{StatusYes, "The dedicated transaction-recovery capability, leader-only ReadIndex path, native shard protocol, and leader-aware gateway executor share exact byte, row, applied-index, and serving-fence bounds. The durable distributed runner consumes those reads while replaying its sealed participant stream.", []Reference{
			ref("gateway/replicated_transaction_recovery.go", "ReadTransactionRecovery"), ref("gateway/replicated_request_transaction_runner.go", "recoverManifestDescriptor"),
		}},
		Shipped: Stage{StatusYes, "vibedb-shard serve-rf3 installs the authenticated recovery reader. vibedb-gateway retries structured requests from replicated ledger state, reuses the sealed program after admission, and exposes terminal ACK plus bounded collection. Recovery authority is replicated; the command installs no same-process registry or periodic process-memory sweep.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("gateway/durable_sql_request_executor.go", "Replay"), ref("gateway/replicated_request_service.go", "Acknowledge"),
		}},
		Qualification: Stage{StatusPartial, "Real RF3 tests prove leader-only recovery, replacement-leader continuity, isolated-former-leader refusal, hidden-commit recovery across two groups, terminal replay through a replacement gateway, and lost committed ACK recovery through a new ledger leader. Durable fault tests cover bounded state, duplicate convergence, ACK tombstones, and restart at every lifecycle cut. TestGatewayDurableRF3ExternalProcessRecovery now exercises the checked-in child-process gateway replacement against real catalog, request-ledger, and two-data-group RF3, including terminal and ACK response loss, ledger-leader kill, exact replay, collection, and every voter restart. Its byte evidence is limited to exact public client request/response wire bytes and snapshot payload bytes, not total network traffic, so the row remains Partial.", []Reference{
			ref("internal/raftservice/owner_rf3_transaction_test.go", "TestRF3TransactionRecoveryReadIsLeaderOnlyAndSurvivesGatewayReplacement"), ref("internal/raftservice/owner_rf3_multigroup_transaction_test.go", "TestTwoRealRF3GroupsExecuteFusedTwoTargetTransactionAcrossLeaderIsolation"), ref("internal/raftservice/owner_rf3_request_ledger_test.go", "TestTwoGatewayDurableSQLRF3RecoversTerminalAndAckAcrossLeaderPartitions"), ref("gateway/replicated_request_ledger_fault_test.go", "TestDurableRequestLostResponseConvergesWhenAnotherGatewayAdvancesAhead"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"),
		}},
	},
	{
		Name: "Durable RF3 request ledger",
		Primitive: Stage{StatusYes, "A replicated request grammar owns paged plans, pending waves, terminal results, acknowledgements, bounded collection, issuer lanes, contiguous issuer high-water, and logical execution pins. Catalog metadata stores adjacent immutable ledger-home ranges with exact RF3 route authority.", []Reference{
			ref("internal/requestledger/command.go", "Command"), ref("gateway/replicated_request_ledger.go", "DurableRequestLedgerTopology"), ref("internal/executionpin/command.go", "Command"),
		}},
		Integrated: Stage{StatusYes, "The typed service selects the catalog-persisted ledger home, seals and streams a logical transaction recipe, recovers lifecycle CAS operations from RF3 state, fences every transaction wave with one execution-pin epoch, derives stable ACK authority, and collects only contiguous GC-complete issuer sequences. The ledger system recovery record region retains a 16 MiB plus 119-sector (16,838,144-byte) compatibility floor, which covers the current 514-entry maximum-key-width conditional record; its owner seals the greater of that floor and the region derived from its actual frozen limits. The 18,360,832-byte hard parser ceiling bounds every owner but is not the ledger's configured allocation. User-relation journals retain their separate 16 MiB plus 34-sector contract.", []Reference{
			ref("gateway/replicated_request_service.go", "NewDurableRequestService"), ref("gateway/replicated_request_lifecycle_runner.go", "NewDurableRequestLifecycleRunner"), ref("gateway/replicated_request_issuer_collector.go", "NewDurableIssuerHighwaterCollector"), ref("sql/driver/replicated_sidecars.go", "canonicalReplicatedApplySidecarsForLimits"), ref("sql/driver/replicated_sidecars.go", "ReplicatedUserRecoveryJournalBytes"), ref("internal/storeio/recovery_journal.go", "RecoveryJournalMaxCapacityBytes"), ref("internal/storeio/recovery_journal_conditional_test.go", "TestRecoveryJournalReplicatedLedgerConditionalCeiling"),
		}},
		Shipped: Stage{StatusYes, "vibedb cluster dev provisions a dedicated request-ledger group and shared ACK authority. runServe constructs the RF3 ledger client, catalog-bound topology, execution-pin sessions, distributed runner, replicated issuer authority, strict structured exec_batch service, and ACK collector. Missing durable authority fails startup; no legacy fallback is installed.", []Reference{
			ref("cmd/vibedb/cluster_dev.go", "ensureDevCluster"), ref("internal/gatewayruntime/durable_request_runtime.go", "newReplicatedDurableRuntime"), ref("internal/gatewayruntime/serve.go", "handleConnPolicyDurable"),
		}},
		Qualification: Stage{StatusPartial, "Internal tests prove catalog topology round trips, bounded wide-plan replay, logical-pin fencing, concurrent-gateway convergence, ACK and GC recovery, issuer high-water restart, and strict public wire identity. Real in-process gates add a three-voter ledger, two data groups, full SQL execution, terminal response loss, replacement-gateway replay, authenticated ACK refusal, lost committed ACK recovery, and write-free completed retry. TestGatewayDurableRF3ExternalProcessRecovery now supplies the checked-in child-process gate: three shard processes each host catalog, request-ledger, and two data RF3 groups; distinct gateway principals and route seeds recover lost terminal and ACK responses across a stopped voter, killed leaders, and rolling voter restarts over native mutual TLS. It bounds p99, RSS, allocated storage, WAL allocation, exact public client request/response wire bytes, and snapshot payload bytes, not total Raft or total network bytes, so the row remains Partial.", []Reference{
			ref("gateway/replicated_request_ledger_catalog_test.go", "TestRequestLedgerTopologyCatalogRoundTripAndExactRouteBinding"), ref("gateway/replicated_request_ledger_fault_test.go", "TestDurableRequestConcurrentGatewaysConvergeOnOneOutcome"), ref("gateway/replicated_request_issuer_collector_test.go", "TestDurableIssuerHighwaterCollectorResolvesOutcomeUnknownAndRestart"), ref("internal/raftservice/owner_rf3_request_ledger_test.go", "TestTwoGatewayRequestLedgerRF3RecoversUnknownCreateAcrossLeaderPartition"), ref("internal/raftservice/owner_rf3_request_ledger_test.go", "TestTwoGatewayDurableSQLRF3RecoversTerminalAndAckAcrossLeaderPartitions"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"),
		}},
	},
	{
		Name: "Global exact index routing and maintenance",
		Primitive: Stage{StatusYes, "Catalog metadata, independent index placement, exact lookup, lifecycle fencing, write expansion, and canonical key/before/after mutation-image capture exist.", []Reference{
			ref("gateway/index_metadata.go", "IndexMetadata"), ref("gateway/global_index.go", "GlobalIndexProgram"), ref("sql/driver/mutation_capture.go", "CaptureMutationImagesInto"),
		}},
		Integrated: Stage{StatusYes, "Static planning can select a global index. Static UPDATE and DELETE, including computed UPDATE assignments, capture canonical images on the base shard, bind old and postimage digests around the original SQL, and order all index deletes before puts. Static and RF3 writes add independently placed index participants without forcing the base row onto the index shard. RF3 exact-key direct and computed updates retain a canonical postimage plus exact old-value CAS; global indexes are derived from that postimage, and a same-key locator refresh uses one digest-compare replacement.", []Reference{
			ref("gateway/executor.go", "captureIndexedMutation"), ref("gateway/writer.go", "bindGlobalIndexCapture"), ref("gateway/transaction.go", "sortTransactionTargets"), ref("gateway/replicated_sql_transaction.go", "planReplicatedSQLTransaction"),
		}},
		Shipped: Stage{StatusYes, "The static gateway command consumes ready global-index metadata, exposes exact lookup, and maintains computed-update indexes through one single-base-owner exec whose index writes may add transaction participants. The durable RF3 exec_batch lane and gateway pgwire autocommit lane lower ready unique and non-unique index maintenance for exact-key whole-document, direct-column, and supported computed declared-column updates into relation-aware transaction participants. RF3 RETURNING remains fenced.", []Reference{
			ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("gateway/executor.go", "captureIndexedMutation"), ref("gateway/replicated_sql_transaction.go", "planReplicatedSQLTransaction"), ref("gateway/upsert_conflict_test.go", "TestPostgreSQLRF3PreparesComputedUpdateAndKeepsReturningFenced"),
		}},
		Qualification: Stage{StatusPartial, "Local tests cover static capture without publication, computed simultaneous updates, malformed-image refusal, base/postimage digest guards, unique swaps, cross-statement delete-before-put ordering, RF3 retained computed postimages, index derivation, same-key locator replacement, routing, lifecycle, and rollback. A mandatory external process gate churns cross-hosted unique and non-unique RF3 indexes with two base tables across partition, leader kill, gateway replacement, exact retry, ACK/GC, and all-voter reopen, but it uses whole-document updates rather than computed expressions. The static computed path also lacks an external fault gate, and required Ubuntu RF3 evidence is not yet recorded, so this remains Partial.", []Reference{
			ref("sql/driver/mutation_capture_images_test.go", "TestMutationImageCaptureEvaluatesComputedUpdateOnceAndPublishesNothing"), ref("shardservice/mutation_capture_images_test.go", "TestMutationCaptureWireReturnsExactImagesWithoutPublication"), ref("gateway/global_index_test.go", "TestComputedUpdateGlobalIndexCaptureUsesShardPostimage"), ref("gateway/global_index_test.go", "TestComputedUpdateGlobalIndexCaptureOrdersUniqueSwapDeletesBeforePuts"), ref("gateway/global_index_test.go", "TestStaticTransactionOrdersGlobalIndexDeletesAcrossStatements"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLComputedUpdateDerivesGlobalIndexFromRetainedPostimage"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLComputedPostimageIsOwnedByDurableLogicalProgram"), ref("internal/replicatedstate/relation_bundle_test.go", "TestGlobalDigestCompareProvesSameLocatorAndReplacesExactOldLocator"), ref("internal/gatewayruntime/durable_rf3_multirelation_chaos_process_test.go", "TestGatewayDurableRF3MultiRelationChaosProcess"),
		}},
	},
	{
		Name: "Atomic multi-relation replicated apply",
		Primitive: Stage{StatusYes, "One replicated command can bind and atomically apply dense JSON and global-index relation batches with one result.", []Reference{
			ref("internal/replicatedstate/relation_bundle.go", "RelationCollection"), ref("internal/replication/command.go", "RelationBatchView"),
		}},
		Integrated: Stage{StatusYes, "The replicated state machine validates the relation manifest and commits all relation targets with its system state.", []Reference{
			ref("internal/replicatedstate/machine.go", "Machine"), ref("internal/replicatedstate/relation_bundle_test.go", "TestRelationBundleAtomicBaseLocalAndGlobalIndexApply"),
		}},
		Shipped: Stage{StatusYes, "vibedb-shard prepare-rf3 creates and serve-rf3 opens an exact replicated SQL/apply bundle. vibedb-gateway can lower exact-key mutations for multiple RF3 base-table relations into the same participant without table or SQL strings entering Raft.", []Reference{
			ref("cmd/vibedb-shard/prepare_rf3.go", "runPrepareRF3"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("gateway/replicated_sql_transaction.go", "planReplicatedSQLTransaction"),
		}},
		Qualification: Stage{StatusPartial, "Deterministic apply, replay, malformed-command, failure-atomic, multi-table lowering, RF3 global-index lowering, exact same-key locator replacement, and deterministic transaction-refusal normalization tests exist. A mandatory external process gate issues 60 insert, update, and delete mutations over two tables, two data groups, and four cross-hosted index relations while injecting a bidirectional Raft peer-network partition with the isolated process live, leader kill, gateway replacement, exact outcome-unknown retry, ACK/GC, and every-voter reopen. Exact final base cardinality and stale/new index visibility are checked, but the updates are whole-document rather than computed. Qualification remains Partial until Ubuntu records three unskipped runs.", []Reference{
			ref("internal/replicatedstate/relation_bundle_test.go", "TestRelationBundleCheckpointCrashPhasesNeverRecoverSkew"), ref("internal/replicatedstate/relation_bundle_test.go", "TestGlobalDigestCompareProvesSameLocatorAndReplacesExactOldLocator"), ref("internal/replicatedstate/transaction_apply_integration_test.go", "TestTransactionPrepareNormalizesMutationRefusalsToExactConflictVote"), ref("gateway/replicated_sql_transaction_test.go", "TestReplicatedSQLTransactionRoutesReadyGlobalIndexAsIndependentRF3Target"), ref("internal/gatewayruntime/durable_rf3_multirelation_chaos_process_test.go", "TestGatewayDurableRF3MultiRelationChaosProcess"),
		}},
	},
	{
		Name: "RF3 proposal serving and exact retry",
		Primitive: Stage{StatusYes, "Bounded proposal admission, Raft quorum, durable committed apply, settlement waiters, and request identity exist.", []Reference{
			ref("internal/raftservice/owner.go", "Owner"), ref("internal/raftserve/registry.go", "Waiter"),
		}},
		Integrated: Stage{StatusYes, "Authenticated peer runtime, replicated shard service, and native gateway executor form a complete internal RF3 path.", []Reference{
			ref("internal/raftservice/peer.go", "AuthenticatedPeerRuntime"), ref("gateway/replicated_native.go", "ReplicatedExecutor"),
		}},
		Shipped: Stage{StatusYes, "vibedb-shard prepare-rf3 atomically creates one stable three-voter member root. serve-rf3 opens either that singleton manifest or 1..64 retained group bundles, routes each group through one of 1..64 deterministic execution lanes (default 8), shares one authenticated per-peer transport across all lanes, and serves the authenticated native endpoint. With -reload-prepared-groups, SIGHUP may append already prepared groups from the same manifest while preserving retained bundles, process configuration, and roster; removal, replacement, enrolled targets, identity/path reuse, drift, and more than 64 groups are refused. Group-scoped snapshot and replica-control services support multi-group enrolled targets over shared physical listeners. The manifest bound is per process, not a transaction participant or cluster-wide shard limit.", []Reference{
			ref("cmd/vibedb-shard/prepare_rf3.go", "runPrepareRF3"), ref("cmd/vibedb-shard/serve_rf3.go", "runServeRF3"), ref("cmd/vibedb-shard/rf3_reload_groups.go", "reloadPreparedRF3Groups"),
		}},
		Qualification: Stage{StatusPartial, "Preparation and manifest gates prove restartable artifact publication, overwrite refusal, canonical multi-group parsing, group-scaled serving bounds, explicit power-of-two lane counts, and append-only reload validation. A checked-in composition gate with three processes proves retained-state opening, mutual TLS, natural election, authenticated reads, and clean process shutdown. Internal gates additionally enumerate all eight three-voter reachability masks, prove majority commit and minority fail-closed behavior, benchmark execution-lane scaling and hot-group isolation, and cover follower catch-up, response loss, exact retry, and acknowledged-result survival. TestGatewayDurableRF3ExternalProcessRecovery adds a checked-in multi-group process gate: each of three shard processes hosts four independent RF3 groups while stopped and killed voters, exact terminal and ACK retries, gateway replacement, rolling restarts, and hard p99, RSS, allocation, public-client-wire, and snapshot-payload bounds are exercised. It does not measure total network bytes. Qualification remains Partial because external live-SIGHUP reload, exhaustive quorum/apply cuts, and 64-group process scaling remain absent.", []Reference{
			ref("cmd/vibedb-shard/prepare_rf3_test.go", "TestPrepareRF3PublishesCompleteRestartableMemberAndReopensExactly"), ref("cmd/vibedb-shard/rf3_manifest_test.go", "TestParseRF3ManifestCanonicalMultiGroupBundles"), ref("cmd/vibedb-shard/serve_rf3_test.go", "TestRF3ExecutionLaneCountIsExplicitPowerOfTwo"), ref("cmd/vibedb-shard/serve_rf3_test.go", "TestRF3MultiGroupServingLimitsCoverManifestBound"), ref("cmd/vibedb-shard/rf3_reload_groups_test.go", "TestRF3ReloadOnlyAppendsIndependentPreparedGroups"), ref("cmd/vibedb-shard/serve_rf3_process_test.go", "TestServeRF3ShippedCompositionThreeProcesses"), ref("internal/raftservice/process_rf3_test.go", "TestRF3NativeServingThreeProcessRecoveryEvidence"), ref("internal/raftservice/owner_rf3_test.go", "TestAuthenticatedThreeVoterServingPutSurvivesLeaderLossAndExactRetry"), ref("internal/raftservice/owner_rf3_multigroup_transaction_test.go", "TestRF3AllThreeVoterQuorumCutsFailClosedOrCommit"), ref("internal/multiraft/lanes_test.go", "BenchmarkExecutionLanesScaling"), ref("internal/multiraft/lanes_test.go", "BenchmarkExecutionLanesSixtyFourGroups"), ref("internal/multiraft/lanes_test.go", "BenchmarkExecutionLanesHotShardIsolation"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"),
		}},
	},
	{
		Name: "Development cluster and Kubernetes test tooling",
		Primitive: Stage{StatusYes, "A local RF1 development/no-HA or RF3 process orchestrator, deterministic Helm-free Kubernetes manifest renderer, and secure disposable-cluster authority generator exist.", []Reference{
			ref("cmd/vibedb/cluster_dev.go", "runClusterDev"), ref("internal/kubeoperator/render.go", "Render"), ref("internal/kubeoperator/bootstrap.go", "Bootstrap"),
		}},
		Integrated: Stage{StatusYes, "The local command generates credentials, policy, WAL and shared ACK material, portable schema witnesses, distinct retained catalog, request-ledger, and data roots, a strict canonical replica-control inventory, and a private mutable route-seed path for the gateway. Every serving process has one unambiguous authenticated NodeID/control listener. RF3 supervises three voters per role plus one gateway and enables catalog-authorized hot-shard split admission. It publishes no replica-move candidates because the dev topology has no certified cold target host. RF1 supervises one no-HA member per role without a gateway. Catalog genesis stores one immutable proof atomically with the first head and witness; the route seed advances independently of immutable genesis and only from authenticated certified heads. The Kubernetes lane composes stable DNS, PVCs, disruption budgets, shard and gateway StatefulSets, and a scale-zero learner bootstrap template.", []Reference{
			ref("cmd/vibedb/cluster_dev.go", "ensureDevCluster"), ref("internal/kubeoperator/render.go", "Render"),
		}},
		Shipped: Stage{StatusYes, "vibedb cluster dev --replicas 1|3 starts or resumes the same three-role topology. RF1 has three single-voter role processes and no gateway. RF3 has nine retained members with distinct NodeIDs across independent catalog, request-ledger, and data groups plus one gateway; it passes generated authenticated split-only replica-control and hot-shard capacity manifests plus a private route-seed path derived by appending `.route-seed` to the catalog path. vibedb-operator bootstrap, render, and prepare provide crash-resumable test authority, deterministic Kubernetes manifests, and idempotent ordinal preparation. The renderer is not a reconciliation watch-loop, and Kubernetes DNS is discovery rather than leader or topology authority.", []Reference{
			ref("cmd/vibedb/main.go", "run"), ref("cmd/vibedb-operator/main.go", "bootstrap"), ref("cmd/vibedb-operator/main.go", "render"), ref("cmd/vibedb-operator/main.go", "prepare"),
		}},
		Qualification: Stage{StatusPartial, "Tests prove canonical local-cluster resume, three independent apply roles and NodeIDs, canonical replica-control generation, portable replica schema witnesses, ledger-only capacity, data-only table publication, explicit RF1/RF3 validation, production-policy compatibility, child reaping, distinct loopback endpoints, deterministic Kubernetes output, secure bootstrap recovery, and injection rejection. One mandatory Linux gate drives authenticated durable pressure through the zero-config process topology and requires a serving child split under hard resource bounds. A separate no-skip three-worker Kind gate now requires stable DNS, ten retained PVC identities, one acknowledged write, every RF3 and gateway ordinal rolling restart, exact terminal retry, row visibility, and hard p99, maximum-latency, RSS, apparent-storage, and WAL bounds. The claim remains Partial until these new gates pass CI. There is no retained prior-binary fixture or negotiated mixed-format protocol, so no honest rolling-format compatibility gate can be constructed yet; the Kubernetes lane also does not prove gateway HA, involuntary partitions, cloud volumes, or production PKI lifecycle.", []Reference{
			ref("cmd/vibedb/cluster_dev_test.go", "TestDevClusterManifestResumeIsCanonicalAndDoesNotReprovision"), ref("cmd/vibedb/cluster_dev_test.go", "TestInitializeDevClusterEmitsThreeIndependentApplyRoles"), ref("internal/gatewayruntime/hot_shard_dev_process_test.go", "TestGatewayZeroConfigDevPressureCompletesReplicatedSplit"), ref("cmd/vibedb/cluster_dev_test.go", "TestDevRequestLedgerPrepareProfileMatchesCatalogHomeAndKeepsCatalogDisabled"), ref("cmd/vibedb/cluster_dev_test.go", "TestDevReplicatedTableProfileUsesPortableSchemaAcrossReplicaLocalStores"), ref("cmd/vibedb/cluster_dev_test.go", "TestDevCatalogPublishesOnlyThePortableDataTableProfile"), ref("internal/kubeoperator/bootstrap_test.go", "TestBootstrapRecoversEveryPublicationCut"), ref("internal/kubeoperator/render_test.go", "TestRenderRF3GoldenAndSafetyContract"), ref("cmd/vibedb-kube-qualify/main.go", "runClient"),
		}},
	},
	{
		Name: "Automatic Raft WAL retention",
		Primitive: Stage{StatusYes, "Checkpoint-bound WAL generation preparation, authenticated selection, publication, settlement, and old-generation replacement exist.", []Reference{
			ref("internal/raftstore/generation_activate.go", "GenerationActivation"), ref("internal/raftmember/generation_driver.go", "WALGenerationDriverOptions"),
		}},
		Integrated: Stage{StatusYes, "Each RF3 runtime captures and prepares generation authority on its owner lane, builds one immutable candidate on a bounded background worker, revalidates the checkpoint before publication, and retries post-selection settlement without blocking Raft progress.", []Reference{
			ref("internal/raftmember/generation_driver.go", "ConfigureWALGeneration"), ref("internal/raftmember/generation_driver_test.go", "TestRuntimeWALGenerationBuildDoesNotBlockRaftProgress"),
		}},
		Shipped: Stage{StatusYes, "serve-rf3 enables checkpoint-driven WAL generation maintenance on a fixed logical cadence and settles an authenticated selecting generation before runtime adoption after restart.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "rf3WALGenerationIntervalTicks"), ref("internal/raftmember/generation_driver.go", "ConfigureWALGeneration"),
		}},
		Qualification: Stage{StatusPartial, "Repeated generation, idle, restart, selected-generation recovery, and blocked-build progress tests exist. A mandatory external RF3 crash loop restarts every replica across three cycles and enforces retained-WAL growth, retained/live ratio, waiter, RSS, descriptor, p99, and maximum-latency bounds. Qualification remains Partial because the external gate covers one fixed three-voter crash-loop profile rather than exhaustive WAL or device fault cuts or mixed-build upgrades.", []Reference{
			ref("internal/raftmember/generation_driver_test.go", "TestRuntimeWALGenerationDriverRepeatedCompactionAndRestart"), ref("cmd/vibedb-shard/wal_retention_process_qualification_test.go", "TestServeRF3WALRetentionCrashQualification"),
		}},
	},
	{
		Name: "Bounded online storage compaction",
		Primitive: Stage{StatusYes, "The durable engine migrates one immutable generation through authenticated adaptive staging extents, rebuilds exact indexes, conditionally swaps the serving root, and retires source, catalog, scratch, chain, and manifest extents without a separate destination collection file.", []Reference{
			ref("store/durable/store_file_online_compact.go", "CompactOnline"), ref("internal/storeio/generation_migration_manifest.go", "GenerationMigrationManifest"),
		}},
		Integrated: Stage{StatusYes, "Collection lifecycle owns explicit crash resume, exact-root reopen, and source retirement. Compaction is single-flight and rejects checkpoint-group ownership. Checkpoint-group seeding cannot attach during an active compaction, and reservation, growth, and retirement recheck ownership.", []Reference{
			ref("store/durable/store_file_online_compact.go", "CompactOnline"),
		}},
		Shipped: Stage{StatusNo, "The public low-level durable API exposes explicit online compaction. The RF3 preparation and serving commands do not select whole-file compaction as an automatic maintenance policy.", nil},
		Qualification: Stage{StatusPartial, "Crash/reopen, opaque and overflow values, exact-index rebuild, atomic retirement, hard apparent/allocated/accounted-payload amplification, and foreground-write p99 gates exist. The accounted device payload omits direct 4 KiB manifest-slot rewrites and is not exact physical device write amplification. There is no checked-in RF3 compaction-under-load gate.", []Reference{
			ref("store/durable/store_file_online_compact_test.go", "TestOnlineCompactionManifestAndChainedExtentSurviveReopen"), ref("store/durable/store_file_online_compact_owner_test.go", "TestCompactOnlineSingleFlight"), ref("store/durable/store_file_online_compact_owner_test.go", "TestCheckpointGroupSeedRejectsActiveOnlineCompaction"), ref("store/durable/store_file_online_compact_owner_test.go", "TestOnlineCompactionPublicationHelpersRejectCheckpointGroupOwner"), ref("store/durable/store_file_online_compact_amplification_unix_test.go", "TestCompactOnlineHardAmplificationGates"), ref("store/durable/store_file_online_compact_amplification_unix_test.go", "TestCompactOnlineForegroundWriteP99Bound"),
		}},
	},
	{
		Name: "Live RF3 backup export",
		Primitive: Stage{StatusYes, "A canonical certificate binds the complete catalog inventory to exact per-group Raft cuts and verified snapshot artifacts. The bounded repository streams operation-scoped drafts and publishes the certificate last without a second artifact copy.", []Reference{
			ref("internal/clusterbackup/certificate.go", "Certificate"), ref("internal/clusterbackup/repository.go", "BackupRepository"), ref("internal/clusterbackup/live_collect.go", "CollectLive"),
		}},
		Integrated: Stage{StatusYes, "The backup controller reads one immutable catalog inventory, resolves and rechecks each authenticated group leader, obtains target-free linearizable exports, persists the complete vector, and conditionally advances one catalog-RF3 operation. Backup capability is independent of data, topology, membership, and serving authority.", []Reference{
			ref("gateway/backup_operation.go", "BackupCatalogCut"), ref("internal/clusterbackup/source_export.go", "ExportLinearizableGroupCut"), ref("internal/gatewayruntime/backup_operator.go", "gatewayBackupOperatorRuntime"),
		}},
		Shipped: Stage{StatusYes, "vibedb-shard serve-rf3 exposes the authenticated target-free backup service. vibedb-gateway serve can open a bounded server-local repository and accepts exact canonical backup and backup_status requests with stable idempotency identity. It rejects static catalog, plaintext, relative paths, incomplete replica control, and missing backup authority.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("internal/gatewayruntime/serve_backup.go", "gatewayBackupWireRequest"),
		}},
		Qualification: Stage{StatusPartial, "Canonical grammar, capability isolation, exact inventory, corruption, wrong-size/hash, partition deadline, repository crash boundaries, partial-draft cleanup, external exit before certificate publication, and no-second-copy collection tests exist. The deterministic exporter reports logical artifact bytes separately from its two scans. There is no mandatory checked-in multi-process foreground-load, leader-loss, retention-release, or restore-readback gate, so qualification remains Partial.", []Reference{
			ref("internal/gatewayruntime/serve_backup_test.go", "TestGatewayBackupRequestUsesDedicatedAuthorityAndCanonicalResponse"), ref("internal/clusterbackup/certificate_test.go", "TestCertificateCanonicalRoundTripAndCompleteCatalogInventory"), ref("internal/clusterbackup/repository_test.go", "TestRepositoryCrashBoundariesNeverExposePartialPublicationOrReleasedBackup"), ref("internal/clusterbackup/live_service_test.go", "TestLiveClientPartitionFailsWithinConfiguredDeadline"), ref("internal/clusterbackup/live_collect_test.go", "TestCollectLiveExternalExitBeforeCertificateRecoversNoBackup"),
		}},
	},
	{
		Name: "Fresh-identity RF3 restore activation",
		Primitive: Stage{StatusYes, "Canonical restore operations bind complete certified backup inventories to fresh cryptographic RF3 group, member, node, and store identities. Authority-free imports support exact singleton and base-plus-global-index relation bundles. The sealed schema set binds every group schema, fresh generation-one catalog, and exact policy. Catalog import discards all source rows and installs only fresh head, witness, genesis, and restore-policy rows. Root witnesses and activation permits bind the complete target set without copying source serving authority.", []Reference{
			ref("internal/clusterrestore/operation.go", "Operation"), ref("internal/clusterrestore/seal.go", "SealFreshOperation"), ref("internal/restoreservice/installer.go", "GroupInstaller"), ref("internal/kubeoperator/restore.go", "RestoreGroup"), ref("gateway/restore_catalog_projection.go", "RestoreCatalogProjection"),
		}},
		Integrated: Stage{StatusYes, "Restore validates the source artifact against the source machine schema and independently derives the fresh target machine manifest, rather than reusing the logical SQL digest. A bounded source-verifying rehash computes unchanged row images under fresh validation profiles. The catalog uses its fresh projection instead. The gateway installs every exact group, publishes a one-time target-catalog RF3 CAS witness through a narrowly fenced activation-only path, separately observes it with ReadIndex, and installs the complete transient per-replica grant vector. Dedicated restore_activate authority, authenticated current-incarnation binding, and immutable restored-root fencing remain required after restart.", []Reference{
			ref("gateway/restore_activation.go", "ActivateRestore"), ref("gateway/replicated_restore_catalog.go", "ReplicatedRestoreCatalog"), ref("internal/clusterrestore/serving_grant.go", "ServingGrant"), ref("shardservice/restore_serving_control.go", "RestoreServingGate"), ref("internal/kubeoperator/restore_bootstrap.go", "RestoreBootstrapOperation"), ref("cmd/vibedb-shard/restore_serving_rf3.go", "rf3RestoreCatalogPreparingAuthority"), ref("sql/driver/replicated_restore_manifest.go", "ReplicatedRelationManifestForBinding"), ref("internal/replicatedstate/restore_manifest.go", "RehashSnapshotArtifact"),
		}},
		Shipped: Stage{StatusYes, "vibedb-operator restore-group constructs three exact non-serving roots from a supplied authenticated operation, artifact, and canonical target-schema set. adopt-restore invokes certified staged-WAL adoption and publishes the manifest last. serve-rf3 enforces immutable restored-root fencing and authenticates transient grants. vibedb-gateway restore-activate consumes one bounded canonical manifest, requires the sealed fresh target catalog, resumes the complete root set, uses real target-catalog RF3 sessions, and installs every serving grant. Operation assembly still uses explicit builder APIs, and production PKI provisioning is not included.", []Reference{
			ref("cmd/vibedb-operator/restore.go", "restoreGroup"), ref("cmd/vibedb-shard/adopt_restored_rf3.go", "adoptRestoredRF3Member"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/gatewayruntime/restore_activate.go", "runRestoreActivate"), ref("internal/gatewayruntime/restore_activate_manifest.go", "parseGatewayRestoreManifest"),
		}},
		Qualification: Stage{StatusPartial, "Tests cover fresh identity, canonical corruption refusal, complete-root certification, every catalog and serving publication cut, exact schema and relation-manifest binding, source-catalog sanitation, staged-WAL adoption, dedicated authorization, response-loss settlement, and process-local grant fencing. A mandatory external process gate boots six real serve-rf3 processes for independent catalog and base/global-index data groups, invokes the actual restore-activate command, proves pre-grant and missing-marker refusal, observes real target-catalog RF3 activation with ReadIndex, verifies fresh catalog and restored base/index data, preserves an acknowledged write across leader SIGKILL, and requires re-observation and regrant after restart under aggregate latency, RSS, storage, and WAL bounds. Qualification remains Partial because cross-build schema migration and production certificate provisioning remain unsupported.", []Reference{
			ref("internal/clusterrestore/controller_process_linux_test.go", "TestActivationExternalProcessRecoversEveryPublicationCutWithinBounds"), ref("internal/restoreservice/installer_linux_test.go", "TestGroupInstallerBuildsAndRecoversThreeAuthorityFreeRoots"), ref("internal/kubeoperator/restore_bundle_linux_test.go", "TestRestoreReplicaFactoryBindsExactBundle"), ref("internal/kubeoperator/restore_catalog_projection_test.go", "TestRestoreCatalogProjectionIsOperationBoundAndExcludesSourceAuthority"), ref("sql/driver/replicated_restore_projection_test.go", "TestReplicatedRestoreProjectionDropsSourceRowsAndResumes"), ref("cmd/vibedb-shard/adopt_restored_rf3_test.go", "TestRestoredRosterMatchesOnlyAuthenticatedTargets"), ref("gateway/replicated_restore_catalog_test.go", "TestReplicatedRestoreCatalogSettlesResponseLossByLinearizableRead"), ref("cmd/vibedb-shard/restore_rf3_process_test.go", "TestRestoredRF3ExternalProcessServingAndFailover"),
		}},
	},
	{
		Name: "Raft linearizable and follower point reads",
		Primitive: Stage{StatusYes, "Leader reads use ReadIndex. Follower reads require explicit applied-position and serving fences. Serving probes read a fixed-width durable authorization fence without acquiring collection snapshots or scanning hidden rows. Successful reads preserve the admitted request fence at the returned applied cut instead of taking a post-read probe.", []Reference{
			ref("internal/raftservice/owner.go", "ReadPoint"), ref("internal/raftservice/owner.go", "syncCommandFenceFromSnapshot"), ref("internal/multiraft/host.go", "ReadIndex"), ref("shardservice/replicated_server.go", "replicatedReadState"),
		}},
		Integrated: Stage{StatusYes, "Replicated table profiles bind a public table and one scalar string/number ordered placement key to exact routes. The gateway follows leaders, refreshes a definitely stale catalog route once, and can select a sufficiently applied follower for the explicit follower contract. Composite and tenant-path placement keys remain absent.", []Reference{
			ref("gateway/replicated_data_read.go", "ReplicatedDataReader"), ref("gateway/replicated_table.go", "ResolveReplicatedTableKey"),
		}},
		Shipped: Stage{StatusYes, "vibedb-gateway serves canonical point get requests through the authenticated RF3 native pool when it consumes the replicated catalog. Linearizable reads use ReadIndex. Monotonic follower reads require the exact RouteID and applied index. The point API never falls back to SQL; replicated-catalog query uses a separate RF3 SELECT transport.", []Reference{
			ref("internal/gatewayruntime/serve.go", "handleConnPolicy"), ref("gateway/replicated_data_read.go", "Read"),
		}},
		Qualification: Stage{StatusPartial, "Command-boundary tests cover canonical decoding, typed results, authorization, no SQL fallback, coalesced catalog refresh, follower selection, route mismatch, serving fences, successful-read no-post-probe behavior, duplicate-release-safe aggregate response reservations, direct zero-allocation response streaming, and blocked-client write timeout. TestGatewayDurableRF3ExternalProcessRecovery issues public-gateway linearizable point reads while one shard process is SIGSTOP-partitioned, requires two-voter leaders for all four groups, verifies post-commit readback, and includes the reads in bounded failover and foreground p99 evidence. Qualification remains Partial because external follower-staleness latency and exhaustive partition cuts remain absent.", []Reference{
			ref("internal/gatewayruntime/data_handler_test.go", "TestHandleConnDataDispatchesRF3ReadWithoutSQLFallback"), ref("gateway/replicated_data_read_test.go", "TestReplicatedDataReaderLinearizableRefreshesNotLeader"), ref("internal/raftservice/owner_rf3_query_probe_test.go", "TestRF3SQLReadUsesAcceptedFenceWithoutPostProbe"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"),
		}},
	},
	{
		Name: "Learner promotion, removal, and leader transfer",
		Primitive: Stage{StatusYes, "ConfChange, learner roles, durable promotion evidence, removal, and leader transfer exist in the Raft runtime.", []Reference{
			ref("internal/multiraft/host.go", "ProposeConfChange"), ref("internal/multiraft/host.go", "TransferLeader"),
		}},
		Integrated: Stage{StatusYes, "The durable move controller owns learner add, snapshot/catch-up waits, promotion, conditional leader transfer, ownership publication, two catalog-drain fences, source removal, retirement, grant finalization, and restart resume. Certified failures across independent groups are admitted as one atomic catalog operation set before any learner action begins.", []Reference{
			ref("internal/rebalanceexec/executor.go", "ExecuteReplicaMove"), ref("internal/rebalanceexec/controller.go", "SubmitSet"), ref("internal/rebalanceexec/controller.go", "RunPass"),
		}},
		Shipped: Stage{StatusYes, "serve-rf3 exposes authenticated membership, observation, snapshot-source, ownership, and retirement control. vibedb-gateway starts the resumable move controller when a strict replica-control manifest is present.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/gatewayruntime/replica_health_controller.go", "startGatewayReplicaControllers"), ref("internal/gatewayruntime/standalone_flags.go", "runServe"),
		}},
		Qualification: Stage{StatusPartial, "Deterministic action tests cover the complete ordered lifecycle and real hosts cover authenticated transfer with continued apply. A mandatory Linux CI gate runs three physical voters, one shared-listener cold target, and one checked-in gateway command across two independent groups; it requires atomic move-set discovery, snapshot bootstrap, catch-up, promotion, catalog publication, source removal, controller SIGKILL/restart, certified cleanup, non-rejoin, and hard admission, p50/p99/max, network, storage, WAL, RSS, and cleanup bounds. The claim remains Partial until that new gate passes CI; failure replacement correctly retains the already-elected live leader, while planned live-source moves exercise conditional leader transfer separately.", []Reference{
			ref("internal/rebalanceexec/executor_test.go", "TestExecutorMapsExactMembershipSnapshotWaitAndDrainActions"), ref("internal/multiraft/host_leader_transfer_real_test.go", "TestThreeRealHostsTransferLeaderThroughAuthenticatedTransportAndContinueApply"), ref("internal/gatewayruntime/replica_replacement_process_test.go", "TestGatewayAutomaticReplicaReplacementProcesses"),
		}},
	},
	{
		Name: "Online snapshot artifact transfer",
		Primitive: Stage{StatusYes, "A bounded authenticated repository, resumable chunk protocol, descriptor identity, and artifact verification exist.", []Reference{
			ref("internal/snapshottransfer/repository.go", "Repository"), ref("internal/snapshottransfer/service.go", "Receiver"),
		}},
		Integrated: Stage{StatusYes, "Artifact production, authenticated transport, crash-safe empty-learner activation, exact-incarnation adoption, Multi-Raft host addition, catch-up observation, and later promotion are composed by the durable move controller.", []Reference{
			ref("internal/snapshottransfer/learner_install.go", "InstallPublishedLearner"), ref("internal/rebalanceexec/executor.go", "ExecuteReplicaMove"),
		}},
		Shipped: Stage{StatusYes, "serve-rf3 exposes authenticated bounded, group-scoped source-control and snapshot-data listeners. bootstrap-rf3 receives, verifies, installs, and resumes one or more cold learners through one physical NodeID/control listener before reopening every installed group through the ordinary serving command.", []Reference{
			ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("cmd/vibedb-shard/bootstrap_rf3.go", "bootstrapPreparedRF3"), ref("cmd/vibedb-shard/bootstrap_rf3_groups.go", "bootstrapPreparedRF3Groups"),
		}},
		Qualification: Stage{StatusPartial, "Resume, disconnect, corruption, bounds, TLS rotation, activation-seam fault settlement, post-Host-add rejection reopen, exact-incarnation retry, and chunk benchmarks exist. Target artifacts use a crash-safe authenticated publish-to-delete transition after learner certification. Completed source exports are released only after the durable target-install witness. Abandoned stages require a canonical catalog-RF3 cancellation witness with the exact operation, step, artifact, source owner epoch, expired lease revision, target incarnation, and schema/replica generations. A bounded gateway scheduler routes that witness to the exact source, and repository tests cover staged and published crash cuts, reopen, idempotent replay, slow-transfer protection, byte ceilings, and retained-byte failure. A Linux-only external multi-process gate now spans two group-scoped learner transfers over shared physical listeners, atomic catalog admission, real catalog cancellation, authenticated source routing, repository rename and unlink crash cuts, target/source/gateway restart, exact cleanup convergence, and hard latency, RSS, network, WAL, and storage bounds. CI requires three unskipped passes; qualification remains Partial until that gate passes there.", []Reference{
			ref("internal/snapshottransfer/source_provider_test.go", "TestRetainedSourceProviderExportsAndObservesAfterReopen"), ref("internal/snapshottransfer/source_control_test.go", "TestSourceControlClientRoutesExactReplicatedAbandonment"), ref("internal/snapshottransfer/abandonment_test.go", "TestRepositoryRecoversEveryAbandonmentNamespacePhase"), ref("internal/rebalanceexec/abandonment_test.go", "TestAbandonmentSchedulerCrashRestartAndByteGateDoNotSkipWitness"), ref("internal/gatewayruntime/replica_replacement_process_test.go", "TestGatewayAutomaticReplicaReplacementProcesses"), ref("internal/snapshottransfer/learner_install_test.go", "TestInstallPublishedLearnerRetriesExactIncarnationAfterHostBoundary"), ref("internal/snapshottransfer/transfer_test.go", "BenchmarkSnapshotServiceChunk"),
		}},
	},
	{
		Name: "Automatic split and replica-move execution",
		Primitive: Stage{StatusYes, "Durable split intent, source capture, immutable artifact construction, tail translation, ownership seal, child staging, RF3 readiness, catalog publication, retained pruning, move plans, failure authorization, and replica-move execution exist. Child image and global-index placement accumulators provide constant-size cut proofs without rescanning relations at cutover.", []Reference{
			ref("internal/splitcontroller/replicated_executor.go", "AdmitReplicatedPlan"), ref("internal/splitcontroller/local_source_actions.go", "LocalSourceActions"), ref("internal/splitcontroller/local_child_actions.go", "LocalChildActions"), ref("internal/rangesplit/stage_image.go", "childStageImageAccumulator"), ref("internal/replicatedstate/relation_placement_accumulator.go", "GlobalIndexPlacementProof"), ref("internal/rebalanceexec/executor.go", "ExecuteReplicaMove"),
		}},
		Integrated: Stage{StatusYes, "For the base-relation split path, the catalog RF3 journal and shard-local durable runtime reconstruct source and child observations, exact action grants, plan admission, capture, artifact, stage, tail, seal, activation, publication, and retained pruning. Pure planning precedes catalog admission; the serving controller persists a pending preparation step before remote child preparation and settles exact receipts before runtime admission. Restart reuses committed intent and receipts without preparing activated or terminal operations again. Global-index relation snapshot partitioning, tail replay, and retained pruning are not integrated. The replica-move path composes failure evidence, candidate selection, membership grants, snapshot bootstrap, catch-up, promotion, catalog drains, removal, and cleanup.", []Reference{
			ref("internal/splitcontroller/committed_preparation.go", "CommittedPlanPreparer"), ref("internal/splitcontroller/committed_preparation_test.go", "TestServingPreparationRequiresCommittedIntentAndResumesLostReceipt"),
			ref("internal/splitcontroller/local_observation_provider.go", "LocalPlanObservationProvider"), ref("internal/splitcontroller/composite_shard_executor.go", "CompositeShardActionExecutor"), ref("internal/splitcontroller/controller_service.go", "NewServingControllerService"), ref("internal/rebalanceexec/controller.go", "Controller"),
		}},
		Shipped: Stage{StatusPartial, "With a strict replica-control manifest, vibedb-gateway reconciles split operations and durable replica moves, and the development path provides hot-split intake. serve-rf3 uses exact per-group child registries and a durable process-wide admission bound. Child SQL preparation supports authenticated base/local/global bundles and partial-schema restart; gateway split_sources carries actual source SQL, local-index definitions, immutable placement, and exact per-source templates with no fallback. Online globally indexed split plans still fail closed: the current artifact and tail path is base-only, and retained pruning rejects index relations. First composed serving-split qualification and repeated descendant discovery, fencing, and restart integration remain pending. Retained-source ownership fencing remains enforced. There is no general operator split CLI.", []Reference{
			ref("internal/rangesplit/artifact.go", "WriteChildArtifacts"), ref("internal/rangesplit/tail.go", "TranslateTailEntry"), ref("internal/splitcontroller/retained_prune_proposer.go", "NewRF3RetainedPruneProposerForPlan"),
			ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("internal/gatewayruntime/split_controller_runtime.go", "gatewayServingSplitRuntime"), ref("internal/gatewayruntime/hot_split_factory.go", "gatewayHotSplitFactory"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("cmd/vibedb-shard/rf3_split_serving.go", "rf3SplitServingRuntime"), ref("internal/gatewayruntime/replica_health_controller.go", "startGatewayReplicaControllers"), ref("internal/replicatedstate/relation_bundle.go", "GlobalIndexProfile"),
		}},
		Qualification: Stage{StatusPartial, "Internal crash matrices cover replicated-journal recovery, durable source capture and seal, child stage and tail retry, publication-before-prune, and post-cutover ownership fencing. Tests cover exact group registry selection and shared operation admission, quorum readiness, O(1) child seal/activation, and constant-size global-index ownership proof. Committed-preparation tests cover lost receipts, forged cursors, and restart after receipts before settlement. Mandatory Linux process gates define split-under-load leader-kill, partition, reopen, p99, RSS, storage, WAL, exact public-wire, and snapshot-payload requirements; current failing or pending runs do not qualify the first serving split or repeated descendants. The initial partition is one bounded scan, and crash recovery may audit the sealed image. Qualification remains Partial until required unskipped Ubuntu runs pass. Range-scan routing proof remains absent.", []Reference{
			ref("internal/splitcontroller/committed_preparation_test.go", "TestCommittedPreparationRejectsForgedReservedCursorBeforeEffects"), ref("internal/splitcontroller/committed_preparation_test.go", "TestCommittedPreparationCrashAfterReceiptsBeforeCompletionRecord"),
			ref("cmd/vibedb-shard/rf3_group_child_preparer_test.go", "TestRF3GroupChildRegistrySelectionBindsExactGroupProfileAndPaths"), ref("cmd/vibedb-shard/rf3_group_child_preparer_test.go", "TestRF3GroupChildPreparationHasOneGlobalOperationBound"),
			ref("internal/splitcontroller/local_source_actions_test.go", "TestLocalSourceActionsRecoverCaptureAndPublishImmutableArtifacts"), ref("internal/splitcontroller/local_source_seal_test.go", "TestLocalSourceSealAndCutoverCertificateSurviveRestart"), ref("internal/splitcontroller/reconcile_test.go", "TestChildActionsRequireMonotonicExactEvidence"), ref("internal/rangesplit/stage_image_incremental_test.go", "TestChildStageSealDoesNotScanRows"), ref("internal/splitcontroller/global_index_cut_test.go", "TestGlobalIndexCutUsesCanonicalUniqueAndNonUniquePlacementAtBoundary"), ref("internal/splitcontroller/execute_test.go", "TestPublishBeforePruneCrashMatrixNeverLosesOrDoubleRoutesRows"), ref("internal/gatewayruntime/hot_shard_mutation_process_test.go", "TestGatewayHotShardMutationProcesses"), ref("internal/gatewayruntime/hot_shard_dev_process_test.go", "TestGatewayZeroConfigDevPressureCompletesReplicatedSplit"),
		}},
	},
	{
		Name: "Replicated catalog and distributed DDL",
		Primitive: Stage{StatusYes, "A dedicated RF3 catalog authority provides linearizable catalog heads, an atomic immutable generation-one proof, sealed authenticated head receipts, crash-safe mutable route-seed staging and promotion, and bounded resumable operation records. Exact schema rollout primitives prepare immutable shard bundles, bind per-group receipts, authorize one catalog cut, activate it, drain the prior generation, and support pre-activation abort.", []Reference{
			ref("gateway/replicated_catalog_authority.go", "ReplicatedCatalogAuthority"), ref("gateway/replicated_catalog_route_seed.go", "ReplicatedCatalogRouteSeedState"), ref("gateway/replicated_catalog_route_seed.go", "StageReplicatedCatalogRouteSeedAfter"), ref("gateway/schema_rollout.go", "PrepareSchemaRollout"), ref("internal/schemainstall/installer.go", "Installer"),
		}},
		Integrated: Stage{StatusYes, "Route-seed control installation performs one attested catch-up read before serving. After installation, every subsequent authenticated catalog read and publication crosses one certified-head observer before holder exposure. Byte-identical heads avoid disk I/O; newer exact-self-route heads promote live. Any catalog self-route change durably stages the candidate, seals authority, signals shutdown, and requires quiescence plus old-session Retire, Release, journal destruction, and candidate promotion before restart. Catalog publication, topology journals, schema rollout records, shard installers, and authenticated control services retain exact catalog, group, relation-manifest, and contract digests.", []Reference{
			ref("gateway/replicated_catalog_route_seed.go", "InstallReplicatedCatalogRouteSeed"), ref("gateway/replicated_catalog_route_seed.go", "CompleteQuiescedHandoff"), ref("gateway/schema_rollout_controller.go", "NewSchemaRolloutController"), ref("internal/schemainstall/control.go", "NewControlService"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/gatewayruntime/schema_rollout_admin.go", "executeGatewaySchemaRollout"),
		}},
		Shipped: Stage{StatusYes, "Replicated gateway mode requires an immutable -catalog genesis and a distinct private -catalog-route-seed. On a certified catalog self-route change, runServe drains public and control users, settles the old native session, promotes the staged seed, and exits with the typed restart-required error for supervisor restart; startup resumes every pending/journal crash cut. vibedb cluster dev automatically derives the private route-seed path by appending `.route-seed` to the catalog path. serve-rf3 installs the authenticated schema control service. Startup authenticates an exact committed source N+1 transition, opens only a fenced recovery handle, settles local catalog publication, closes the source, and opens the target before runtime adoption. The experimental schema-rollout command conditionally publishes one exact catalog successor; it is not a general SQL DDL endpoint or a completed repeated-rollout lifecycle.", []Reference{
			ref("cmd/vibedb-shard/schema_startup_recovery.go", "openRF3RetainedApply"), ref("sql/driver/schema_catalog_source_recovery.go", "OpenReplicatedShardStoreWithSchemaSourceTransition"),
			ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("internal/gatewayruntime/serve.go", "recoverReplicatedCatalogRouteSeedStartup"), ref("cmd/vibedb/cluster_dev.go", "ensureDevCluster"), ref("cmd/vibedb-shard/serve_rf3.go", "servePreparedRF3"), ref("internal/gatewayruntime/command.go", "run"), ref("internal/gatewayruntime/schema_rollout_admin.go", "executeGatewaySchemaRollout"),
		}},
		Qualification: Stage{StatusPartial, "Catalog tests cover quorum publication, leader loss, sealed-receipt rejection, same-route live promotion, self-route-change staging, preauthorized-mutator refusal, path aliasing, near-maximum heads, and startup recovery. The external durable RF3 gate adds distinct gateway route seeds and catalog-voter failure. Initial route helpers distinguish logical SQL and exact machine manifests. Schema tests cover activation, restart, pre-activation abort, mixed-old/new refusal, authenticated control, installer reopen, command-plan validation, and leader-loss recovery. Directory publication and retry sync fixes are implemented; local normal and race tests cover exact committed-source recovery and settlement before runtime adoption, while the physical Linux startup gate remains unqualified. The schema digest caller audit, post-drain replacement of write-once rollout artifacts, and trusted retained-identity rollover for repeated DDL remain incomplete. No external self-route-change handoff, rolling mixed-build, or SQL DDL rollback gate exists.", []Reference{
			ref("internal/replicatedstate/schema_source_recovery_test.go", "TestSchemaSourceRecoveryAuthenticatesCommittedCheckpoint"), ref("internal/replicatedstate/schema_source_recovery_test.go", "TestSchemaRetiredSourceRejectsServingOperations"), ref("cmd/vibedb-shard/schema_startup_recovery_test.go", "TestRF3SchemaStartupSettlementFailsClosedAtEveryBoundary"), ref("cmd/vibedb-shard/schema_startup_recovery_linux_test.go", "TestRF3SchemaStartupSettlesCommittedSourceBeforeRuntimeAdoption"),
			ref("sql/driver/replicated_manifest_test.go", "TestInitialReplicatedRelationManifestMatchesServingIdentity"), ref("internal/replicatedstate/initial_manifest_test.go", "TestInitialJSONRelationManifestMatchesPreparedCollection"),
			ref("gateway/replicated_catalog_authority_test.go", "TestReplicatedCatalogRouteSeedTrackerPersistsSameRouteBeforeHolderPublish"), ref("gateway/replicated_catalog_authority_test.go", "TestReplicatedCatalogRouteSeedTrackerStagesAndSignalsBeforeChangedHolder"), ref("gateway/replicated_catalog_authority_test.go", "TestReplicatedCatalogRouteSeedLockedCheckRejectsPreauthorizedWaiter"), ref("internal/gatewayruntime/catalog_route_seed_test.go", "TestRecoverReplicatedCatalogRouteSeedStartupSettlesExactOldBinding"), ref("internal/gatewayruntime/durable_rf3_external_process_test.go", "TestGatewayDurableRF3ExternalProcessRecovery"), ref("gateway/schema_rollout_test.go", "TestSchemaRolloutPrepareActivateExactCatalog"), ref("gateway/schema_rollout_process_test.go", "TestSchemaRolloutExternalProcessLeaderLossAndMixedGenerationRecovery"), ref("internal/schemainstall/installer_test.go", "TestInstallerCrashReopenAuthorizationActivationAndDrain"), ref("internal/gatewayruntime/schema_rollout_admin_test.go", "TestGatewaySchemaRolloutManifestRequiresCanonicalVibeJSON"), ref("internal/raftservice/controlplane_catalog_rf3_test.go", "TestReplicatedCatalogAuthorityRF3QuorumReplayAndControllerRestart"),
		}},
	},
	{
		Name: "Hot-shard detection and rebalancing",
		Primitive: Stage{StatusYes, "Bounded pressure selection, failure-domain placement, split planning, and replica-move selection exist.", []Reference{
			ref("internal/topologyscheduler/admission.go", "SelectSplits"), ref("internal/topologyscheduler/replica_move.go", "SelectReplicaMoves"),
		}},
		Integrated: Stage{StatusYes, "Routed requests feed bounded per-allocation recorders. A collector publishes canonical pressure cuts through catalog RF3. A clockless controller qualifies sustained pressure, selects either a split or replica move, and hands one idempotent admission to the existing operation journals.", []Reference{
			ref("internal/hotshard/collector.go", "Collector"), ref("internal/hotshard/controller.go", "Controller"), ref("internal/hotshard/operation_sink.go", "OperationSink"),
		}},
		Shipped: Stage{StatusPartial, "With -hot-shard-capacity and an authenticated replica-control manifest, vibedb-gateway records routed pressure, publishes canonical catalog-RF3 cuts, and submits idempotent split or certified replica-move work. Exact source SQL, local indexes, immutable placement, and separate logical/machine schema digests support schema-bundle preparation, not completed global-index split execution. Serving startup restores certified adopted groups from a bounded live inventory. Catalog admission precedes remote preparation and local tests cover exact source/catalog fences; relation-aware global-index snapshot/tail/prune, repeated descendant capture, and gateway source-discovery qualification remain incomplete. External split and restart qualification is still required.", []Reference{
			ref("internal/gatewayruntime/hot_shard_runtime.go", "gatewayHotShardRuntime"), ref("internal/gatewayruntime/hot_shard_runtime.go", "runPressurePass"), ref("internal/gatewayruntime/standalone_flags.go", "runServe"), ref("cmd/vibedb/cluster_dev.go", "ensureDevCluster"),
		}},
		Qualification: Stage{StatusPartial, "Deterministic tests cover sustained-hotness qualification, logical cooldown, clock-skew refusal, failure domains, capacity and retained-memory bounds, zero-allocation foreground intake, and byte-identical outcome-unknown retry. Mandatory Linux external-process gates drive real multi-table and global-index mutations through the checked-in gateway command into catalog-RF3 pressure, one automatic certified replica move across leader loss, response partition, and process reopen, and one zero-config terminal split. They enforce hard p99, RSS, allocated-storage, WAL-allocation, request-count, exact public client request/response wire-byte, and snapshot-payload-byte ceilings; they do not measure total network traffic. Qualification remains Partial until the mandatory unskipped Ubuntu evidence is recorded.", []Reference{
			ref("internal/hotshard/controller_test.go", "TestControllerQualifiesHotShardAndRetriesByteIdenticalAdmission"), ref("internal/hotshard/controller_test.go", "TestControllerClockSkewCannotAdvanceReplicatedEvidence"), ref("internal/gatewayruntime/hot_shard_runtime_test.go", "TestGatewayHotShardPressurePassCreatesExactEnrolledReplicaMove"), ref("internal/gatewayruntime/hot_shard_shipped_e2e_test.go", "TestGatewayHotShardForegroundP99Overhead"), ref("internal/gatewayruntime/hot_shard_mutation_process_test.go", "TestGatewayHotShardMutationProcesses"), ref("internal/gatewayruntime/hot_shard_dev_process_test.go", "TestGatewayZeroConfigDevPressureCompletesReplicatedSplit"),
		}},
	},
}
