#!/usr/bin/env bash
set -euo pipefail

# Development/test qualification only. Identity and authority material is
# generated by vibedb-operator; this script never manufactures credentials.
cluster_name=vibedb-qualification
namespace=vibedb-test
image=vibedb:kube-qualification
root_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
evidence_dir=${VIBEDB_KUBE_EVIDENCE_DIR:-"${RUNNER_TEMP:-/tmp}/vibedb-kube-rf3-evidence"}
work_dir=$(mktemp -d "${RUNNER_TEMP:-/tmp}/vibedb-kube-rf3.XXXXXXXX")
state_dir="${work_dir}/bootstrap-authority"
bootstrap_yaml="${work_dir}/bootstrap.yaml"
topology_yaml="${work_dir}/topology.yaml"
bootstrap_metadata="${work_dir}/bootstrap-metadata.txt"
port_forward_pid=

start_port_forward() {
  if [[ -n "${port_forward_pid}" ]]; then
    kill "${port_forward_pid}" >/dev/null 2>&1 || true
    wait "${port_forward_pid}" >/dev/null 2>&1 || true
  fi
  kubectl port-forward -n "${namespace}" service/vibedb-gateway 17400:7400 \
    >> "${evidence_dir}/port-forward.log" 2>&1 &
  port_forward_pid=$!
}

cleanup() {
  if [[ -n "${port_forward_pid}" ]]; then
    kill "${port_forward_pid}" >/dev/null 2>&1 || true
    wait "${port_forward_pid}" >/dev/null 2>&1 || true
  fi
  kind delete cluster --name "${cluster_name}" >/dev/null 2>&1 || true
}
trap cleanup EXIT

for command_name in go docker kind kubectl base64; do
  command -v "${command_name}" >/dev/null
done
if kind get clusters | grep -Fqx "${cluster_name}"; then
  echo "refusing to replace existing kind cluster ${cluster_name}" >&2
  exit 1
fi
mkdir -p "${evidence_dir}"
git -C "${root_dir}" rev-parse HEAD > "${evidence_dir}/revision.txt"
go version > "${evidence_dir}/go-version.txt"
kind version > "${evidence_dir}/kind-version.txt"
kubectl version --client=true > "${evidence_dir}/kubectl-version.txt"

go build -o "${work_dir}/vibedb-operator" "${root_dir}/cmd/vibedb-operator"
go build -o "${work_dir}/vibedb-kube-qualify" "${root_dir}/cmd/vibedb-kube-qualify"
mkdir -m 0700 "${state_dir}"
"${work_dir}/vibedb-operator" bootstrap \
  -namespace "${namespace}" -state-dir "${state_dir}" \
  > "${bootstrap_yaml}" 2> "${bootstrap_metadata}"
"${work_dir}/vibedb-operator" render -namespace "${namespace}" -image "${image}" \
  -bootstrap-state-dir "${state_dir}" > "${topology_yaml}"
"${work_dir}/vibedb-operator" validate -manifest "${topology_yaml}"
kubectl apply --dry-run=client --validate=false -f "${bootstrap_yaml}" >/dev/null
kubectl apply --dry-run=client --validate=false -f "${topology_yaml}" >/dev/null

docker build --file "${root_dir}/deploy/kubernetes/Dockerfile" --tag "${image}" "${root_dir}"
kind create cluster --name "${cluster_name}" \
  --config "${root_dir}/deploy/kubernetes/kind-3-worker.yaml" --wait 120s
kind load docker-image --name "${cluster_name}" "${image}"

kubectl create namespace "${namespace}"
kubectl apply -f "${bootstrap_yaml}"
kubectl apply -f "${topology_yaml}"
for role in catalog ledger data gateway; do
  kubectl rollout status -n "${namespace}" "statefulset/vibedb-${role}" --timeout=10m
done
kubectl exec -n "${namespace}" vibedb-gateway-0 -- \
  vibedb-kube-qualify dns -namespace "${namespace}" -timeout 60s \
  | tee "${evidence_dir}/dns.vibejson"

kubectl get pvc -n "${namespace}" -o custom-columns=NAME:.metadata.name,UID:.metadata.uid \
  --no-headers | LC_ALL=C sort > "${evidence_dir}/pvc-before.tsv"
test "$(wc -l < "${evidence_dir}/pvc-before.tsv")" -eq 10

for key_name in client-cert.pem client-key.pem cluster-roots.pem; do
  kubectl get secret -n "${namespace}" vibedb-qualification-client-tls \
    -o "go-template={{index .data \"${key_name}\"}}" \
    | base64 --decode > "${work_dir}/${key_name}"
done
chmod 0600 "${work_dir}/client-key.pem"
start_port_forward

"${work_dir}/vibedb-kube-qualify" write \
  -certificate "${work_dir}/client-cert.pem" -key "${work_dir}/client-key.pem" \
  -roots "${work_dir}/cluster-roots.pem" \
  -bootstrap-state "${state_dir}/bootstrap-state.vibejson" \
  -state "${work_dir}/acknowledged-request.vibejson" \
  -samples 128 -max-p99 1s -max-latency 5s \
  | tee "${evidence_dir}/before-restart.vibejson"

# Exercise every ordinal, including whichever member currently leads, while
# StatefulSet readiness keeps each RF3 group from voluntarily losing quorum.
for role in catalog ledger data gateway; do
  kubectl rollout restart -n "${namespace}" "statefulset/vibedb-${role}"
  kubectl rollout status -n "${namespace}" "statefulset/vibedb-${role}" --timeout=10m
done
start_port_forward

"${work_dir}/vibedb-kube-qualify" verify \
  -certificate "${work_dir}/client-cert.pem" -key "${work_dir}/client-key.pem" \
  -roots "${work_dir}/cluster-roots.pem" \
  -bootstrap-state "${state_dir}/bootstrap-state.vibejson" \
  -state "${work_dir}/acknowledged-request.vibejson" \
  -samples 128 -max-p99 1s -max-latency 5s \
  | tee "${evidence_dir}/after-restart.vibejson"

kubectl get pvc -n "${namespace}" -o custom-columns=NAME:.metadata.name,UID:.metadata.uid \
  --no-headers | LC_ALL=C sort > "${evidence_dir}/pvc-after.tsv"
cmp "${evidence_dir}/pvc-before.tsv" "${evidence_dir}/pvc-after.tsv"
for role in catalog ledger data; do
  for ordinal in 0 1 2; do
    pod="vibedb-${role}-${ordinal}"
    kubectl exec -n "${namespace}" "${pod}" -- \
      vibedb-kube-qualify measure -root /var/lib/vibedb \
      -max-rss-bytes $((1 << 30)) -max-storage-bytes $((1 << 30)) \
      -max-wal-bytes $((512 << 20)) \
      | tee "${evidence_dir}/${pod}.vibejson"
  done
done
kubectl exec -n "${namespace}" vibedb-gateway-0 -- \
  vibedb-kube-qualify measure -root /var/lib/vibedb \
  -max-rss-bytes $((1 << 30)) -max-storage-bytes $((1 << 30)) \
  -max-wal-bytes $((512 << 20)) \
  | tee "${evidence_dir}/vibedb-gateway-0.vibejson"

kubectl get pods -n "${namespace}" -o wide > "${evidence_dir}/pods.txt"
kubectl get events -n "${namespace}" --sort-by=.lastTimestamp > "${evidence_dir}/events.txt"
echo "Kubernetes RF3 qualification passed; evidence=${evidence_dir}"
