// Authoritative Vitess-derived golden vectors for the vitessroute adapter.
//
// The committed testdata/*.jsonl vectors are generated by running REAL upstream
// Vitess (v0.22.0) via the regenerate path below; they are NOT hand-written and
// NOT derived from the adapter. TestGoldenVectors re-drives upstream on every
// run and asserts the committed bytes still match it (pin integrity) AND that
// the adapter reproduces them exactly (compatibility). A mismatch is a STOP
// CONDITION: fix the adapter, or, only for a deliberate pinned-version change,
// regenerate with VITESSROUTE_REGENERATE=1 under review. Never edit a committed
// vector by hand to make a test pass.

package vitessroute

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/thesyncim/vibedb/distribution"
)

const (
	xxhashGoldenFile   = "testdata/xxhash_golden.jsonl"
	multicolGoldenFile = "testdata/multicol_golden.jsonl"
	regenerateEnv      = "VITESSROUTE_REGENERATE"
)

const goldenHeader = `# AUTHORITATIVE Vitess-derived compatibility golden vectors.
#
# Provenance: generated by driving real upstream Vitess vitess.io/vitess
# v0.24.2 (go/vt/vtgate/vindexes {xxhash,multicol,cfc}.go) from golden_test.go.
# The design pins v0.22.0; the reproduced vindex algorithms are byte-identical
# from v0.22.0 through v0.24.2 (v0.22.0's go/hack does not compile under Go 1.26
# because the swissmap GOEXPERIMENT was removed), so these vectors are exactly
# what v0.22.0 produces. These bytes are placement identity: the same logical
# value must reach the same shard forever. They are NOT hand-written and NOT
# derived from the reimplementation.
#
# A mismatch in TestGoldenVectors is a STOP CONDITION, not an edit target: it
# means either the adapter regressed against upstream, or the pinned Vitess
# version changed. Fix the adapter. Do NOT edit a vector to silence a failure.
# Regenerate ONLY for a reviewed, intentional pinned-version change by running
# 'VITESSROUTE_REGENERATE=1 go test ./...' in this module. The pinned upstream
# version lives in this module's go.mod (vitess.io/vitess), never in the root.
#
# Anchors (xxhash 8-byte keyspace id, hex):
#   xxhash("tenant-42") = 404f5103a9b9fbf9
#   xxhash(int 12345)   = b64fd60addd2f2c6
#
# Format: one JSON object per line; '#' and blank lines are ignored. A str input
# carries its raw bytes as hex; an int input carries its canonical decimal. A
# point dest is the 8-byte keyspace id in hex; a range dest is start/end in hex
# with end "MAX" denoting the open maximum (2^64).
`

// goldenCase is one representative vector to persist. For xxhash, inputs has one
// element; for multicol, 1..count elements (a full key or a leading prefix).
type goldenCase struct {
	vindex string // "xxhash" | "multicol"
	count  int    // multicol column_count
	bytes  string // multicol column_bytes ("" = default distribution)
	inputs []scalarInput
}

// goldenCorpus is the frozen representative subset. Adding cases is fine (then
// regenerate); changing an existing case's meaning is a compatibility break.
func goldenCorpus() []goldenCase {
	var cases []goldenCase
	for _, s := range stringCorpus() {
		cases = append(cases, goldenCase{vindex: "xxhash", count: 1, inputs: []scalarInput{strIn(s)}})
	}
	for _, n := range numberCorpus() {
		cases = append(cases, goldenCase{vindex: "xxhash", count: 1, inputs: []scalarInput{n}})
	}

	// Representative multicol full keys and leading prefixes (points and ranges).
	mc := func(count int, bytes string, ins ...scalarInput) goldenCase {
		return goldenCase{vindex: "multicol", count: count, bytes: bytes, inputs: ins}
	}
	// count=1, width 8: full key only (equivalent to a bare xxhash point).
	cases = append(cases, mc(1, "8", strIn("tenant-42")))
	// count=2, 4,4: prefix (range) and full key (point), string and int columns.
	cases = append(cases,
		mc(2, "4,4", strIn("tenant-42")),
		mc(2, "4,4", strIn("tenant-42"), strIn("channel-7")),
		mc(2, "4,4", intIn("12345", 12345)),
		mc(2, "4,4", intIn("12345", 12345), intIn("67890", 67890)),
		mc(2, "4,4", strIn("")),
		mc(2, "4,4", strIn(""), intIn("0", 0)),
	)
	// count=2 default (4,4) to pin the defaulted distribution.
	cases = append(cases,
		mc(2, "", strIn("日本語")),
		mc(2, "", strIn("日本語"), uintIn("18446744073709551615", 1<<64-1)),
	)
	// count=3, 2,3,3: two prefix lengths and a full key.
	cases = append(cases,
		mc(3, "2,3,3", strIn("tenant-42")),
		mc(3, "2,3,3", strIn("tenant-42"), intIn("12345", 12345)),
		mc(3, "2,3,3", strIn("tenant-42"), intIn("12345", 12345), strIn("bucket-3")),
	)
	// count=3 default (3,3,2) full key.
	cases = append(cases, mc(3, "", strIn("a"), strIn("b"), strIn("c")))
	return cases
}

func (gc goldenCase) computeUpstream(t *testing.T) distribution.DestinationSet {
	t.Helper()
	if gc.vindex == "xxhash" {
		return upstreamXXHash(t, newUpstreamXXHash(t), gc.inputs[0].upstreamValue())
	}
	mc := newUpstreamMultiCol(t, gc.count, gc.bytes)
	return upstreamMultiCol(t, mc, upstreamRow(gc.inputs))
}

func (gc goldenCase) computeAdapter(t *testing.T) distribution.DestinationSet {
	t.Helper()
	var (
		ds  distribution.DestinationSet
		err error
	)
	if gc.vindex == "xxhash" {
		ds, err = NewXXHashMapper().MapPrefix([]distribution.Scalar{gc.inputs[0].adapterScalar(t)})
	} else {
		ds, err = adapterMultiColMapper(t, gc.count, gc.bytes).MapPrefix(adapterScalars(t, gc.inputs))
	}
	if err != nil {
		t.Fatalf("adapter mapping failed for %s: %v", gc.describe(), err)
	}
	return ds
}

func (gc goldenCase) describe() string {
	if gc.vindex == "xxhash" {
		return "xxhash " + strings.Join(describeRow(gc.inputs), ",")
	}
	return fmt.Sprintf("multicol(count=%d,bytes=%s) %s", gc.count, orDefault(gc.bytes), strings.Join(describeRow(gc.inputs), ","))
}

// ---- On-disk record schema ----

type gInput struct {
	T   string `json:"t"`             // "str" | "int"
	Hex string `json:"hex,omitempty"` // str: hex of raw bytes
	Dec string `json:"dec,omitempty"` // int: canonical decimal
}

type gDest struct {
	Kind  string `json:"kind"`            // "point" | "range"
	Ksid  string `json:"ksid,omitempty"`  // point: 16-hex keyspace id
	Start string `json:"start,omitempty"` // range: 16-hex start
	End   string `json:"end,omitempty"`   // range: 16-hex end, or "MAX"
}

type gRecord struct {
	Vindex      string   `json:"vindex"`
	ColumnCount int      `json:"column_count,omitempty"`
	ColumnBytes string   `json:"column_bytes,omitempty"`
	Inputs      []gInput `json:"inputs"`
	Dest        gDest    `json:"dest"`
}

func (gc goldenCase) inputRecords() []gInput {
	out := make([]gInput, len(gc.inputs))
	for i, in := range gc.inputs {
		if in.isStr {
			out[i] = gInput{T: "str", Hex: hex.EncodeToString([]byte(in.s))}
		} else {
			out[i] = gInput{T: "int", Dec: in.canonicalDecimal()}
		}
	}
	return out
}

func (gc goldenCase) record(dest distribution.DestinationSet) gRecord {
	r := gRecord{Vindex: gc.vindex, Inputs: gc.inputRecords(), Dest: encodeDest(dest)}
	if gc.vindex == "multicol" {
		r.ColumnCount = gc.count
		r.ColumnBytes = gc.bytes
	}
	return r
}

func encodeDest(d distribution.DestinationSet) gDest {
	switch {
	case len(d.Points) == 1 && len(d.Ranges) == 0:
		return gDest{Kind: "point", Ksid: hex.EncodeToString(d.Points[0][:])}
	case len(d.Ranges) == 1 && len(d.Points) == 0:
		r := d.Ranges[0]
		end := "MAX"
		if !r.End.Max {
			end = hex.EncodeToString(r.End.Point[:])
		}
		return gDest{Kind: "range", Start: hex.EncodeToString(r.Start[:]), End: end}
	default:
		return gDest{Kind: fmt.Sprintf("invalid(points=%d,ranges=%d)", len(d.Points), len(d.Ranges))}
	}
}

// ---- Test ----

func TestGoldenVectors(t *testing.T) {
	cases := goldenCorpus()
	var xxCases, mcCases []goldenCase
	for _, gc := range cases {
		if gc.vindex == "xxhash" {
			xxCases = append(xxCases, gc)
		} else {
			mcCases = append(mcCases, gc)
		}
	}

	if os.Getenv(regenerateEnv) == "1" {
		writeGolden(t, xxhashGoldenFile, xxCases)
		writeGolden(t, multicolGoldenFile, mcCases)
		t.Logf("regenerated %d xxhash and %d multicol golden vectors from upstream Vitess", len(xxCases), len(mcCases))
	}

	verifyGolden(t, xxhashGoldenFile, xxCases)
	verifyGolden(t, multicolGoldenFile, mcCases)
	verifyFileAnchors(t)
}

// writeGolden regenerates a golden file purely from the UPSTREAM computation.
func writeGolden(t *testing.T, path string, cases []goldenCase) {
	t.Helper()
	var buf bytes.Buffer
	buf.WriteString(goldenHeader)
	for _, gc := range cases {
		rec := gc.record(gc.computeUpstream(t))
		line, err := json.Marshal(rec)
		if err != nil {
			t.Fatalf("marshal record for %s: %v", gc.describe(), err)
		}
		buf.Write(line)
		buf.WriteByte('\n')
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir testdata: %v", err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

// verifyGolden asserts the committed file matches BOTH the live upstream result
// and the adapter result, record for record.
func verifyGolden(t *testing.T, path string, cases []goldenCase) {
	t.Helper()
	records := readGolden(t, path)
	if len(records) != len(cases) {
		t.Fatalf("%s has %d records but the corpus has %d cases; regenerate with %s=1 if you intentionally added vectors",
			path, len(records), len(cases), regenerateEnv)
	}
	for i, gc := range cases {
		committed := records[i]

		wantInputs := gc.inputRecords()
		if !reflect.DeepEqual(committed.Inputs, wantInputs) {
			t.Fatalf("%s record %d inputs = %+v, want %+v (case %s)", path, i, committed.Inputs, wantInputs, gc.describe())
		}

		upstream := encodeDest(gc.computeUpstream(t))
		if !reflect.DeepEqual(committed.Dest, upstream) {
			t.Fatalf("%s record %d (%s): committed dest %+v != live upstream %+v — pinned-version drift, STOP",
				path, i, gc.describe(), committed.Dest, upstream)
		}

		adapter := encodeDest(gc.computeAdapter(t))
		if !reflect.DeepEqual(committed.Dest, adapter) {
			t.Fatalf("%s record %d (%s): committed dest %+v != adapter %+v — adapter regressed, STOP (fix the adapter, not the vector)",
				path, i, gc.describe(), committed.Dest, adapter)
		}
	}
}

func readGolden(t *testing.T, path string) []gRecord {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v (regenerate with %s=1)", path, err, regenerateEnv)
	}
	defer f.Close()
	var records []gRecord
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		var r gRecord
		if err := json.Unmarshal([]byte(line), &r); err != nil {
			t.Fatalf("%s: bad JSONL record %q: %v", path, line, err)
		}
		records = append(records, r)
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("scan %s: %v", path, err)
	}
	return records
}

// verifyFileAnchors ties the persisted xxhash file to the two authoritative
// probe anchors: the 8-byte keyspace id, in hex, for the string "tenant-42" and
// the integer 12345.
func verifyFileAnchors(t *testing.T) {
	t.Helper()
	records := readGolden(t, xxhashGoldenFile)
	wantStr := map[string]string{
		hex.EncodeToString([]byte("tenant-42")): "404f5103a9b9fbf9",
	}
	wantInt := map[string]string{
		"12345": "b64fd60addd2f2c6",
	}
	seenStr, seenInt := false, false
	for _, r := range records {
		if r.Vindex != "xxhash" || len(r.Inputs) != 1 || r.Dest.Kind != "point" {
			continue
		}
		in := r.Inputs[0]
		if in.T == "str" {
			if want, ok := wantStr[in.Hex]; ok {
				if r.Dest.Ksid != want {
					t.Fatalf("anchor str keyspace id = %s, want %s", r.Dest.Ksid, want)
				}
				seenStr = true
			}
		} else if in.T == "int" {
			if want, ok := wantInt[in.Dec]; ok {
				if r.Dest.Ksid != want {
					t.Fatalf("anchor int %s keyspace id = %s, want %s", in.Dec, r.Dest.Ksid, want)
				}
				seenInt = true
			}
		}
	}
	if !seenStr || !seenInt {
		t.Fatalf("golden file is missing an anchor vector (str seen=%v, int seen=%v)", seenStr, seenInt)
	}
}

// mustJSON marshals v to JSON bytes for a VSchema literal, failing the test on
// error. Shared with the differential harness.
func mustJSON(t *testing.T, v any) []byte {
	t.Helper()
	data, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal JSON: %v", err)
	}
	return data
}
